(function(){function x(a,c,b){var d=window.__tnetActiveBookmark;if(d){"string"==typeof a&&""!==a&&(d.basemap=a);"string"==typeof c&&""!==c&&(d.basemapColorMode="grey"===c?"grey":"color");try{document.dispatchEvent(new CustomEvent("tnet-bookmark-state-changed",{detail:{reason:b||"basemap-change",bookmark:d}}))}catch{}}}function C(){function a(b){return b>=c.length?(TnetLog.error("[Basemap]","Config nicht gefunden (basemaps.timeDimension)"),Promise.resolve(null)):fetch(c[b]).then(function(d){if(!d.ok)throw Error("HTTP "+
d.status);return d.text()}).then(function(d){return(d=JSON5.parse(d))&&d.basemaps&&d.basemaps.timeDimension?(TnetLog.log("[Basemap]","Config geladen (async):",c[b]),window._basemapTimeConfig=d.basemaps.timeDimension,window._basemapTimeConfig):a(b+1)}).catch(function(d){return TnetLog.warn("[Basemap]","Config-Fehler ("+c[b]+"):",d.message),a(b+1)})}if(window._basemapTimeConfig)return Promise.resolve(window._basemapTimeConfig);if("u"<typeof JSON5)return TnetLog.error("[Basemap]","JSON5-Library nicht verf\u00fcgbar!"),
Promise.resolve(null);var c=[(window.__TNET_APP_ROOT||"/maps")+"/tnet/config/tnet-global-config.json5",(window.__TNET_APP_ROOT||"/maps")+"/tnet/tnet-global-config.json5","../tnet/config/tnet-global-config.json5"];return a(0)}function D(){var a=document.getElementById("basemap_widget");if(a){a.addEventListener("pointerdown",function(b){b.stopPropagation()});a.addEventListener("mousedown",function(b){b.stopPropagation()});a.addEventListener("click",function(b){if(b=b.target.closest(".basemap-card")){var d=
b.dataset.basemap;d&&(b.classList.contains("active")||(document.querySelectorAll(".basemap-card").forEach(function(f){f.classList.remove("active")}),b.classList.add("active"),window.njs&&njs.AppManager&&njs.AppManager.Maps&&njs.AppManager.Maps.main&&(njs.AppManager.Maps.main.changeBaseMap(d),x(d,null,"basemap-change"))))}});var c=a.querySelector(".basemap-expand-header");c&&c.addEventListener("click",function(){var b=a.querySelector(".basemap-cards"),d=this.querySelector(".expand-icon");b&&(b.classList.toggle("expanded"),
d.textContent=b.classList.contains("expanded")?"\u25bc":"\u25b6")})}}function E(){try{var a=Date.now(),c=window.top&&window.top!==window?window.top:null,b=Number(window.__tnetLastRequestedBookmarkAt||c&&c.__tnetLastRequestedBookmarkAt||0);return 0<b&&15E3>a-b?!0:/\/maps(?:-dev)?\/[a-zA-Z0-9_-]+\/?$/.test(String(window.location&&window.location.pathname||""))}catch{return!1}}function F(){var a=function(){if(window.njs&&njs.AppManager&&njs.AppManager.setMapBookmark&&njs.AppManager.infoFloatWinRemoveallItems)if(E()){TnetLog.log("[Basemap]",
"GrundkartenDefaults \u00fcbersprungen (Bookmark-Start aktiv)");var c=njs.AppManager.Maps&&njs.AppManager.Maps.main&&njs.AppManager.Maps.main.mapObj?njs.AppManager.Maps.main.mapObj:null;c&&(window._olMap=c,r(c))}else Object.keys(m).forEach(function(b){try{window.top.njs.AppManager.setMapBookmark(["main"],"layers=-"+m[b])}catch(d){TnetLog.warn("[Basemap]","GrundkartenSync Fehler:",m[b],d)}}),(c=njs.AppManager.Maps&&njs.AppManager.Maps.main&&njs.AppManager.Maps.main.mapObj?njs.AppManager.Maps.main.mapObj:
null)&&(window._olMap=c,TnetLog.log("[Basemap]","window._olMap gesetzt \u2713")),r(c);else setTimeout(a,200)};a()}function r(a){function c(){if(!a)return[];var f=[],e=Object.keys(b);return a.getLayers().forEach(function(g){g.getVisible()&&(g=g.get("name")||g.get("title"))&&-1===e.indexOf(g)&&f.push(g)}),f}var b={};Object.keys(m).forEach(function(f){b[m[f]]=!1});var d=document.querySelectorAll(".toggle-btn[data-layer]");d.forEach(function(f){f.addEventListener("click",function(){var e=this.getAttribute("data-layer"),
g=this.getAttribute("data-value");if(e=m[e])try{b[e]="on"===g;var k=c();Object.keys(b).forEach(function(h){b[h]&&k.push(h)});var l="layers="+k.join("|");window.top.njs.AppManager.setMapBookmark(["main"],l);this.parentElement.querySelectorAll(".toggle-btn").forEach(function(h){h.classList.remove("active")});this.classList.add("active")}catch(h){TnetLog.error("[Basemap]","Layer-Toggle Fehler:",h)}})});TnetLog.log("[Basemap]","GrundkartenSync:",d.length,"Buttons registriert")}function y(){D();F();z.init();
G();TnetLog.log("[Basemap]","Modul vollst\u00e4ndig initialisiert \u2713")}function G(){var a=(new URLSearchParams(window.location.search)).get("basemap");if(a){var c=document.querySelectorAll(".basemap-card[data-basemap]"),b=[];if(c.forEach(function(f){b.push(f.dataset.basemap)}),-1===b.indexOf(a))TnetLog.warn("[Basemap]",'URL basemap="'+a+'" ist ung\u00fcltig. G\u00fcltig:',b.join(", "));else{TnetLog.log("[Basemap]","URL-Parameter basemap="+a);c.forEach(function(f){f.classList.toggle("active",f.dataset.basemap===
a)});var d=0;(function e(){d++;var g=window.njs&&njs.AppManager&&njs.AppManager.Maps&&njs.AppManager.Maps.main,k=g&&"function"==typeof njs.AppManager.Maps.main.changeBaseMap;g&&k?(njs.AppManager.Maps.main.currBasisMap||njs.AppManager.Maps.main.basisMap)!==a?(njs.AppManager.Maps.main.changeBaseMap(a),TnetLog.log("[Basemap]","Basemap aus URL gesetzt:",a)):TnetLog.log("[Basemap]","Basemap aus URL bereits aktiv:",a):40>d?setTimeout(e,500):TnetLog.warn("[Basemap]","Framework nicht bereit, basemap aus URL konnte nicht gesetzt werden")})()}}}
for(var t=[4E3,3750,3500,3250,3E3,2750,2500,2250,2E3,1750,1500,1250,1E3,750,650,500,250,100,50,20,10,5,2.5,2,1.5,1,.5,.25,.1],u=[],v=0;v<t.length;v++)u.push(v.toString());window.SWISSTOPO_RESOLUTIONS=t;window.SWISSTOPO_MATRIX_IDS=u;window.toggleBasemapWidget=function(){var a=document.getElementById("basemap_widget"),c=document.getElementById("basemap_selector");a&&c&&(a.classList.toggle("basemap-widget-hidden"),c.classList.toggle("hidden"))};var m={hoehenkurven:"gis_basis/nw_basisplan_gis_dynamisch/hoehenlinien",
projektebene:"gis_basis/nw_basisplan_gis_dynamisch/grundbuchplan_projektierte_objekte",gemeindegrenzen:"gis_basis/nw_basisplan_gis_dynamisch/gemeindegrenzen"};window.GRUNDKARTEN_LAYER_MAPPING=m;window.setGrundkartenButtonsDefaultAus=function(){Object.keys(m).forEach(function(a){var c=document.getElementById("btn-"+a+"-ein");a=document.getElementById("btn-"+a+"-aus");c&&a&&(c.classList.remove("active"),a.classList.add("active"),c.setAttribute("aria-pressed","false"),a.setAttribute("aria-pressed","true"))})};
window.initGrundkartenLayerSync=r;var z={config:null,currentBasemap:null,currentYear:null,currentYears:[],_timeOverlayLayer:null,containerEl:null,sliderEl:null,labelEl:null,resetBtn:null,minEl:null,maxEl:null,infoEl:null,infoTextEl:null,_currentOpacity:1,_isGrayscale:!1,_grayscaleListeners:{},_grayscaleListenerCnt:0,_grayscaleSourceEntries:[],_hideSliderTimer:null,_hideInfoTimer:null,_moveEndHandler:null,_moveEndDebounceTimer:null,_lastIdentifyCenter:null,init:function(){var a=this;C().then(function(c){(a.config=
c,a.config)?a._initDOM():TnetLog.warn("[Basemap]","Keine timeDimension-Config, Zeitreise deaktiviert")})},_initDOM:function(){var a=this;(this.containerEl=document.getElementById("basemap-time-container"),this.sliderEl=document.getElementById("basemap-time-slider"),this.labelEl=document.getElementById("basemap-time-label"),this.resetBtn=document.getElementById("basemap-time-reset"),this.minEl=document.getElementById("basemap-time-min"),this.maxEl=document.getElementById("basemap-time-max"),this.infoEl=
document.getElementById("basemap-time-info"),this.infoTextEl=document.getElementById("basemap-time-info-text"),this.containerEl&&this.sliderEl)?(a=this,this.sliderEl.addEventListener("input",function(){var c=parseInt(this.value,10);void 0!==a.currentYears[c]&&(a.currentYear=a.currentYears[c],a.updateLabel(a.currentYear),a.applyTimeOverlay(a.currentYear))}),this.resetBtn&&this.resetBtn.addEventListener("click",function(){if(0<a.currentYears.length){var c=a.currentYears.length-1;a.sliderEl.value=c;
a.currentYear=a.currentYears[c];a.updateLabel(a.currentYear);a.applyTimeOverlay(a.currentYear)}}),this._hookOpacityAndGrayscale(),this.hookChangeBaseMap(),TnetLog.log("[Basemap]","Zeitreise initialisiert \u2713")):TnetLog.error("[Basemap]","Zeitreise DOM-Elemente nicht gefunden")},onBasemapChange:function(a){if(this.currentBasemap=a,this._cleanupDynamic(),this.removeTimeOverlay(),this._isGrayscale){var c=this;setTimeout(function(){c.syncGrayscale(!0)},50)}(a=this.config[a])?"info"===a.type?(this.hideSlider(),
this.showInfo(a.infoText||a.label)):(this.hideInfo(),"static"===a.type?(this.currentYears=(a.years||[]).slice().sort(function(b,d){return"string"==typeof b||"string"==typeof d?0:b-d}),this.initSlider(),1<this.currentYears.length?this.showSlider():this.hideSlider(),this.applyTimeOverlay(this.currentYear)):"dynamic"===a.type&&(this.currentYears=(a.fallbackYears||[]).slice().sort(function(b,d){return b-d}),this.initSlider(),this.showSlider(),this.applyTimeOverlay(this.currentYear),this.startDynamicYearFetch(a))):
(this.hideSlider(),this.hideInfo())},initSlider:function(){if(0!==this.currentYears.length){var a=this.currentYears.length-1;this.sliderEl.min=0;this.sliderEl.max=a;this.sliderEl.step=1;this.sliderEl.value=a;this.currentYear=this.currentYears[a];this.minEl&&(this.minEl.textContent=this.currentYears[0]);this.maxEl&&(this.maxEl.textContent=this.currentYears[a]);this.updateLabel(this.currentYear)}},updateLabel:function(a){this.labelEl&&(this.labelEl.textContent=a)},showSlider:function(){this.containerEl&&
(this._hideSliderTimer&&(clearTimeout(this._hideSliderTimer),this._hideSliderTimer=null),this.containerEl.style.display="",this.containerEl.offsetHeight,this.containerEl.classList.add("visible"))},hideSlider:function(){if(this.containerEl){this.containerEl.classList.remove("visible");this._hideSliderTimer&&clearTimeout(this._hideSliderTimer);var a=this.containerEl;this._hideSliderTimer=setTimeout(function(){a.classList.contains("visible")||(a.style.display="none")},400)}},showInfo:function(a){this.infoEl&&
this.infoTextEl&&(this._hideInfoTimer&&(clearTimeout(this._hideInfoTimer),this._hideInfoTimer=null),this.infoTextEl.textContent=a,this.infoEl.style.display="",this.infoEl.offsetHeight,this.infoEl.classList.add("visible"))},hideInfo:function(){if(this.infoEl){this.infoEl.classList.remove("visible");this._hideInfoTimer&&clearTimeout(this._hideInfoTimer);var a=this.infoEl;this._hideInfoTimer=setTimeout(function(){a.classList.contains("visible")||(a.style.display="none")},400)}},applyTimeOverlay:function(a){var c=
this.config[this.currentBasemap];if(c&&c.wmtsUrl){var b;"YYYYMMDD"===c.timestampFormat?b=a+"1231":b=a.toString();var d=c.wmtsUrl.replace("{Time}",b);TnetLog.log("[Basemap]","Overlay:",c.wmtsLayer,"\u2192",b);this._createOverlayLayer(d,b);this._dispatchTimeEvent(a,b)}},_createOverlayLayer:function(a,c){try{var b=njs.AppManager.Maps&&njs.AppManager.Maps.main;if(b&&b.mapObj){var d=b.mapObj;this._removeOverlayFromMap(d);var f=new ol.source.WMTS({url:a,layer:"",matrixSet:"2056",format:"image/png",projection:"EPSG:2056",
requestEncoding:"REST",style:"default",tileGrid:new ol.tilegrid.WMTS({origin:[242E4,135E4],resolutions:t,matrixIds:u}),crossOrigin:"anonymous"}),e=new ol.layer.Tile({source:f,opacity:this._currentOpacity,visible:!0,zIndex:-1});e.set("_isTimeOverlay",!0);e.set("_timeValue",c);d.getLayers().insertAt(0,e);this._timeOverlayLayer=e;this._setBaseLayerVisibility(d,!1);this._isGrayscale&&this._applyGrayscaleViaPrerender(!0)}else TnetLog.warn("[Basemap]","Karte noch nicht bereit \u2013 Overlay wird beim ersten changeBaseMap erstellt")}catch(g){TnetLog.error("[Basemap]",
"Overlay-Layer Fehler:",g)}},_removeOverlayFromMap:function(a){if(a)try{for(var c=a.getLayers().getArray().slice(),b=0;b<c.length;b++)c[b].get("_isTimeOverlay")&&a.removeLayer(c[b])}catch{}},_setBaseLayerVisibility:function(a,c){if(a)try{var b=a.getLayers().getArray();for(a=0;a<b.length;a++){var d=b[a];if(!d.get("_isTimeOverlay")&&d.get("isBaseLayer")){d.setVisible(c);return}}for(d=0;d<b.length;d++)if(!b[d].get("_isTimeOverlay")){b[d].setVisible(c);break}}catch{}},removeTimeOverlay:function(){try{var a=
njs.AppManager.Maps&&njs.AppManager.Maps.main;if(!a||!a.mapObj)return;var c=a.mapObj;this._removeOverlayFromMap(c);this._setBaseLayerVisibility(c,!0)}catch{}this._timeOverlayLayer=null},_hookOpacityAndGrayscale:function(){var a=this;if(njs&&njs.AppManager&&"function"==typeof njs.AppManager.setBaseLayerOpacity){var c=njs.AppManager.setBaseLayerOpacity;njs.AppManager.setBaseLayerOpacity=function(b,d){c.call(njs.AppManager,b,d);"main"===b&&a.syncOpacity(d)};TnetLog.log("[Basemap]","setBaseLayerOpacity gehookt \u2713");
"function"==typeof njs.AppManager.toggleBaseLayerColor&&(a._installFilterStripObserver(),njs.AppManager.toggleBaseLayerColor=function(b,d,f){d=document.querySelectorAll(".ol-basemap");for(var e=0;e<d.length;e++)d[e].classList.remove("grayscale");if(a._stripGrayFilterFromOlLayers(),"main"===b)b=!1,f&&f.getAttribute?b="grey"===f.getAttribute("data-value"):b=!a._isGrayscale,a.syncGrayscale(b),x(null,b?"grey":"color","basemap-color-mode")},TnetLog.log("[Basemap]","toggleBaseLayerColor gehookt \u2713"))}else setTimeout(function(){a._hookOpacityAndGrayscale()},
500)},_stripGrayFilterFromOlLayers:function(){for(var a=document.querySelectorAll(".ol-layer"),c=0;c<a.length;c++){var b=a[c].style;b&&b.filter&&(0<=b.filter.indexOf("gray")||0<=b.filter.indexOf("grey"))&&(b.filter="")}},_captureAndStripGrayFilter:function(){for(var a=document.querySelectorAll(".ol-layer"),c=0;c<a.length;c++){var b=a[c].style;b&&b.filter&&(0<=b.filter.indexOf("gray")||0<=b.filter.indexOf("grey"))&&(b.filter="")}},_installFilterStripObserver:function(){if(!this._filterObserver)try{var a=
new MutationObserver(function(c){for(var b=0;b<c.length;b++){var d=c[b].target;d&&d.classList&&d.classList.contains("ol-layer")&&(d=d.style)&&d.filter&&(0<=d.filter.indexOf("gray")||0<=d.filter.indexOf("grey"))&&(d.filter="")}});a.observe(document.body,{attributes:!0,subtree:!0,attributeFilter:["style"]});this._filterObserver=a}catch(c){TnetLog.warn("[Basemap]","MutationObserver-Setup fehlgeschlagen:",c)}},syncOpacity:function(a){this._currentOpacity=a=1-parseInt(a,10)/100;this._timeOverlayLayer&&
this._timeOverlayLayer.setOpacity(a)},syncGrayscale:function(a){this._isGrayscale=a;try{var c=njs.AppManager.Maps&&njs.AppManager.Maps.main;TnetLog.log("[Basemap]","syncGrayscale:",a,"basemap=",c?c.currBasisMap||c.basisMap||this.currentBasemap:this.currentBasemap,"activeLayers=",this._getActiveBasemapLayers().length,"domTargets=",document.querySelectorAll(".ol-basemap canvas, .ol-basemap img").length)}catch(b){TnetLog.warn("[Basemap]","syncGrayscale Debug-Log Fehler:",b)}this._clearGrayscaleSourceFilters();
this._applyGrayscaleViaPrerender(a)},_clearGrayscaleListeners:function(){for(var a=Object.keys(this._grayscaleListeners),c=0;c<a.length;c++){var b=this._grayscaleListeners[a[c]];try{b.layer.un("prerender",b.pre)}catch{}try{b.layer.un("postrender",b.post)}catch{}try{b.layer.changed()}catch{}}this._grayscaleListeners={}},_clearGrayscaleSourceFilters:function(){for(var a=0;a<this._grayscaleSourceEntries.length;a++){var c=this._grayscaleSourceEntries[a];try{"tile"===c.kind&&c.source.setTileLoadFunction?
c.source.setTileLoadFunction(c.originalFn):"image"===c.kind&&c.source.setImageLoadFunction&&c.source.setImageLoadFunction(c.originalFn),c.source.refresh&&c.source.refresh()}catch(b){TnetLog.warn("[Basemap]","_clearGrayscaleSourceFilters Fehler:",b)}}this._grayscaleSourceEntries=[]},_applyGrayToImageElement:function(a){if(a)try{a.style.filter=this._isGrayscale?"grayscale(100%)":""}catch(c){TnetLog.warn("[Basemap]","_applyGrayToImageElement Fehler:",c)}},_wrapTileLoadFunctionForGrayscale:function(a,
c){var b=this;return function(d,f){c.call(a,d,f);var e=d&&d.getImage?d.getImage():null;e&&(d=function(){b._isGrayscale&&b._applyGrayToImageElement(e)},e.complete&&(e.naturalWidth||e.width)?d():e.addEventListener&&e.addEventListener("load",d,{once:!0}))}},_wrapImageLoadFunctionForGrayscale:function(a,c){var b=this;return function(d,f){c.call(a,d,f);var e=d&&d.getImage?d.getImage():null;e&&(d=function(){b._isGrayscale&&b._applyGrayToImageElement(e)},e.complete&&(e.naturalWidth||e.width)?d():e.addEventListener&&
e.addEventListener("load",d,{once:!0}))}},_applyBasemapSourceGrayscale:function(a){if(this._clearGrayscaleListeners(),this._clearGrayscaleSourceFilters(),a){var c=this._getActiveBasemapLayers();TnetLog.log("[Basemap]","_applyBasemapSourceGrayscale:","layers=",c.length,"grayscale=",a);for(a=0;a<c.length;a++){var b=c[a];if(b=b&&b.getSource?b.getSource():null)try{if(b.setTileLoadFunction&&b.getTileLoadFunction){var d=b.getTileLoadFunction();this._grayscaleSourceEntries.push({source:b,kind:"tile",originalFn:d});
b.setTileLoadFunction(this._wrapTileLoadFunctionForGrayscale(b,d));b.refresh&&b.refresh()}else if(b.setImageLoadFunction&&b.getImageLoadFunction){var f=b.getImageLoadFunction();this._grayscaleSourceEntries.push({source:b,kind:"image",originalFn:f});b.setImageLoadFunction(this._wrapImageLoadFunctionForGrayscale(b,f));b.refresh&&b.refresh()}}catch(e){TnetLog.warn("[Basemap]","_applyBasemapSourceGrayscale Fehler:",e)}}}},_getActiveBasemapLayers:function(){function a(h,n){if(h&&!(0<=b.indexOf(h))&&(b.push(h),
n||!h.get||!h.get("_isTimeOverlay")))if("function"==typeof h.getLayers){h=h.getLayers().getArray();for(var p=0;p<h.length;p++)a(h[p],n)}else c.push(h)}var c=[],b=[];try{var d=njs.AppManager.Maps&&njs.AppManager.Maps.main;if(!d)return c;var f=this.currentBasemap&&this.config?this.config[this.currentBasemap]:null;if(this._timeOverlayLayer&&f&&("static"===f.type||"dynamic"===f.type))return a(this._timeOverlayLayer,!0),c;var e=d.currBasisMap||d.basisMap||this.currentBasemap,g=d.basisMaps&&e?d.basisMaps[e]:
null;if(!g&&d.mapObj&&d.mapObj.getLayers){var k=d.mapObj.getLayers().getArray();for(d=0;d<k.length;d++){var l=k[d];if(l&&l.get&&l.get("isBaseLayer")&&!l.get("_isTimeOverlay")){g=l;break}}}a(g)}catch(h){TnetLog.warn("[Basemap]","_getActiveBasemapLayers Fehler:",h)}return c},_applyGrayscaleViaPrerender:function(a){if(this._clearGrayscaleListeners(),a)try{var c=this,b=this._getActiveBasemapLayers();if(b.length)for(a=0;a<b.length;a++)(function(d){var f=function(k){try{k.context&&(k.context.filter="grayscale(1)")}catch{}},
e=function(k){try{k.context&&(k.context.filter="none")}catch{}};d.on("prerender",f);d.on("postrender",e);var g="gl"+c._grayscaleListenerCnt++;c._grayscaleListeners[g]={layer:d,pre:f,post:e};try{d.changed()}catch{}})(b[a])}catch(d){TnetLog.warn("[Basemap]","_applyGrayscaleViaPrerender Fehler:",d)}},_applyBasemapGrayscaleCSS:function(a){var c=this._getActiveBasemapLayers();TnetLog.log("[Basemap]","_applyBasemapGrayscaleCSS:","layers=",c.length,"grayscale=",a);for(var b=0;b<c.length;b++)this._applyBasemapLayerFilter(c[b],
a)},_applyBasemapLayerFilter:function(a,c){if(a){var b=c?"grayscale(100%)":"",d=!1,f=function(g){if(!g||!g.querySelectorAll)return!1;g=g.querySelectorAll("canvas, img");if(!g.length)return!1;for(var k=0;k<g.length;k++)g[k].style.filter=b;return!0};try{var e=a.getRenderer?a.getRenderer():null;e&&(d=f(e.container)||d,d=f(e.element)||d,!d&&e.canvas&&(e.canvas.style.filter=b,d=!0))}catch(g){TnetLog.warn("[Basemap]","_applyBasemapLayerFilter Fehler:",g)}TnetLog.log("[Basemap]","_applyBasemapLayerFilter:",
"applied=",d,"grayscale=",c)}},_applyBasemapDomGrayscale:function(a){a=a?"grayscale(100%)":"";var c=document.querySelectorAll(".ol-basemap canvas, .ol-basemap img");TnetLog.log("[Basemap]","_applyBasemapDomGrayscale:","targets=",c.length,"filter=",a||"(leer)");for(var b=0;b<c.length;b++)c[b].style.filter=a},_applyGrayscaleCSS:function(a,c){if(a){var b=c?"grayscale(100%)":"",d=function(g){return g?(g.style.filter=b,!0):!1},f=function(g){if(!g||!g.querySelectorAll)return!1;g=g.querySelectorAll("canvas, img");
if(!g.length)return!1;for(var k=0;k<g.length;k++)g[k].style.filter=b;return!0};try{var e=a.getRenderer?a.getRenderer():null;if(e&&(f(e.container)||f(e.element)||e.canvas&&d(e.canvas)||d(e.container)||d(e.element)||e.canvas&&d(e.canvas.parentElement||e.canvas)))return}catch{}setTimeout(function(){try{var g=njs.AppManager.Maps&&njs.AppManager.Maps.main;if(g&&g.mapObj){var k=g.mapObj,l=a.getRenderer?a.getRenderer():null;if(!(l&&(f(l.container)||f(l.element)||l.canvas&&d(l.canvas))||l&&d(l.container||
l.element))){var h=k.getViewport().querySelectorAll(".ol-layer canvas, .ol-layer img");0<h.length&&d(h[0])}}}catch(n){TnetLog.warn("[Basemap]","Grayscale CSS Fallback Fehler:",n)}},150)}},_dispatchTimeEvent:function(a,c){var b=this.config[this.currentBasemap]||{};document.dispatchEvent(new CustomEvent("basemap-time-change",{detail:{basemapId:this.currentBasemap,year:a,timeValue:c,wmtsUrl:b.wmtsUrl||null,timestampFormat:b.timestampFormat||null}}))},startDynamicYearFetch:function(a){var c=this;this.fetchDynamicYears(a);
try{var b=njs.AppManager.Maps&&njs.AppManager.Maps.main,d=b?b.mapObj:null;d&&(this._moveEndHandler=function(){c._moveEndDebounceTimer&&clearTimeout(c._moveEndDebounceTimer);c._moveEndDebounceTimer=setTimeout(function(){c.fetchDynamicYears(a)},a.moveEndDebounce||500)},d.on("moveend",this._moveEndHandler))}catch(f){TnetLog.warn("[Basemap]","moveend error:",f)}},fetchDynamicYears:function(a){var c=this;try{var b=njs.AppManager.Maps&&njs.AppManager.Maps.main;if(b&&b.mapObj){var d=b.mapObj,f=d.getView(),
e=f.getCenter(),g=f.calculateExtent(d.getSize());if(this._lastIdentifyCenter){var k=Math.abs(e[1]-this._lastIdentifyCenter[1]);if(100>Math.abs(e[0]-this._lastIdentifyCenter[0])&&100>k)return}this._lastIdentifyCenter=e.slice();var l=a.identifyUrl+"?layers="+encodeURIComponent(a.identifyParams.layers)+"&geometry="+e[0].toFixed(0)+","+e[1].toFixed(0)+"&geometryType="+a.identifyParams.geometryType+"&mapExtent="+g.map(function(h){return h.toFixed(0)}).join(",")+"&imageDisplay="+a.identifyParams.imageDisplay+
"&tolerance="+a.identifyParams.tolerance+"&lang=de";fetch(l).then(function(h){return h.json()}).then(function(h){h=c._extractYearsFromIdentify(h);0<h.length&&c._updateDynamicSlider(h)}).catch(function(h){TnetLog.warn("[Basemap]","Identify error:",h)})}}catch(h){TnetLog.warn("[Basemap]","fetchDynamicYears error:",h)}},_extractYearsFromIdentify:function(a){var c={};try{var b=a.results||[];for(a=0;a<b.length;a++){var d=b[a].attributes||b[a].properties||{},f=d.array_release_years;if(Array.isArray(f))for(var e=
0;e<f.length;e++)"number"==typeof f[e]&&(c[f[e]]=!0);d.release_year&&(c[d.release_year]=!0)}}catch{}return Object.keys(c).map(Number).sort(function(g,k){return g-k})},_updateDynamicSlider:function(a){var c=this.currentYear;this.currentYears=a;var b=a.length-1;if(this.sliderEl.min=0,this.sliderEl.max=b,null!==c){var d=a.indexOf(c);0<=d?(this.sliderEl.value=d,this.currentYear=c):(c=this._findNearest(a,c),this.sliderEl.value=a.indexOf(c),this.currentYear=c)}else this.sliderEl.value=b,this.currentYear=
a[b];this.minEl&&(this.minEl.textContent=a[0]);this.maxEl&&(this.maxEl.textContent=a[b]);this.updateLabel(this.currentYear)},_findNearest:function(a,c){for(var b=a[0],d=Math.abs(c-a[0]),f=1;f<a.length;f++){var e=Math.abs(c-a[f]);e<d&&(d=e,b=a[f])}return b},_cleanupDynamic:function(){if(this._moveEndHandler){try{var a=njs.AppManager.Maps&&njs.AppManager.Maps.main,c=a?a.mapObj:null;c&&c.un("moveend",this._moveEndHandler)}catch{}this._moveEndHandler=null}this._moveEndDebounceTimer&&(clearTimeout(this._moveEndDebounceTimer),
this._moveEndDebounceTimer=null);this._lastIdentifyCenter=null},hookChangeBaseMap:function(){function a(){if(b++,njs&&njs.AppManager&&njs.AppManager.Maps&&njs.AppManager.Maps.main){var d=njs.AppManager.Maps.main;if(!d._basemapTimeHooked){var f=d.changeBaseMap;d._basemapTimeHooked=!0;d._preTimeChangeBaseMap=f;d.changeBaseMap=function(g){c.removeTimeOverlay();var k=g,l=c.config?c.config[g]:null;l&&l.fallbackBasemap&&(k=l.fallbackBasemap);TnetLog.log("[Basemap]","changeBaseMap:",g,"\u2192 Framework:",
k);l=!1;try{var h=d.mapObj.getLayers(),n=d.basisMaps[k];if(n)if(h.item(0)===n)TnetLog.log("[Basemap]","Basemap-Layer bereits an Position 0, \u00fcberspringe Framework-Aufruf"),l=!0;else for(var p=h.getArray(),q=1;q<p.length;q++)if(p[q]===n){h.removeAt(q);TnetLog.warn("[Basemap]","Basemap-Layer an Position",q,"entfernt (war deplatziert)");break}}catch{}var A;return l||(A=d._preTimeChangeBaseMap.call(d,k)),setTimeout(function(){var w=d.mapObj;if(w){var B=w.getViewport();B&&(B.ondragstart=function(H){H.preventDefault()});
w.updateSize()}c.onBasemapChange(g)},200),A};TnetLog.log("[Basemap]","changeBaseMap gehookt \u2713");var e=d.currBasisMap||d.basisMap;e?(TnetLog.log("[Basemap]","Framework-Basemap beim Hook:",e),document.querySelectorAll(".basemap-card").forEach(function(g){g.classList.toggle("active",g.dataset.basemap===e)}),c.onBasemapChange(e)):(f=document.querySelector(".basemap-card.active"))&&f.dataset.basemap&&c.onBasemapChange(f.dataset.basemap)}}else 30>b?setTimeout(a,500):TnetLog.warn("[Basemap]","Hook aufgegeben nach",
30,"Versuchen")}var c=this,b=0;a()},getCurrentTimeValue:function(){if(!this.currentYear||!this.currentBasemap)return null;var a=this.config[this.currentBasemap];return a&&"info"!==a.type?"YYYYMMDD"===a.timestampFormat?this.currentYear+"1231":this.currentYear.toString():null},getCurrentWmtsUrl:function(){return this.currentBasemap&&this.config[this.currentBasemap]?this.config[this.currentBasemap].wmtsUrl||null:null}};window.BasemapTimeManager=z;"loading"===document.readyState?document.addEventListener("DOMContentLoaded",
y):y()})();
