(function(){function v(){return window.__TNET_APP_ROOT||"/maps"}function z(){return TnetIcons.get("legend-colors",null,{width:"14",height:"14",style:"vertical-align:-2px"})}function w(){return'<svg width="11" height="13" viewBox="0 0 11 13" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><rect x="1" y="5.5" width="9" height="6.5" rx="1" stroke="currentColor" stroke-width="1.2"/><path d="M3 5.5V3.5a2.5 2.5 0 0 1 5 0v2" stroke="currentColor" stroke-width="1.2"/></svg>'}function l(a){return a||
0===a?(A||=document.createElement("div"),A.textContent=String(a),A.innerHTML):""}var h=null,B=null,r=null,x={},t=[],y="",u=null,p={},C={nidwalden:{label:"Nidwalden",wappen:v()+"/tnet/resources/wappen_nidwalden.svg"},obwalden:{label:"Obwalden",wappen:v()+"/tnet/resources/wappen_obwalden.svg"},bund:{label:"Bundesdaten",wappen:v()+"/tnet/resources/wappen_bund.svg"},weitere:{label:"Weitere Geodaten",wappen:v()+"/tnet/resources/icon_weitere.svg"}},D={nidwalden:"Nidwalden",obwalden:"Obwalden",bund:"Bundesdaten",
weitere:"Weitere Geodaten"},A=null;window.TnetLMTree={init:function(a){if(h=document.getElementById(a),h){var d=window.TnetLMStore;if(d){t.push(d.on("catalog-loaded",this.render.bind(this)));t.push(d.on("layer-visibility",this._onLayerVisibility.bind(this)));t.push(d.on("layer-loading",this._onLayerLoading.bind(this)));t.push(d.on("active-layers-changed",this._onActiveLayersChanged.bind(this)));t.push(d.on("group-toggled",this._onGroupToggled.bind(this)));var b=this,c=function(){b._syncToActiveBookmark()};
document.addEventListener("tnet-bookmark-loaded",c);t.push(function(){document.removeEventListener("tnet-bookmark-loaded",c)});d.isLoaded()&&this.render(d.getCatalog());this._initResolutionWatch();window.__tnetActiveBookmark&&this._syncToActiveBookmark();TnetLog.log("[LM-Tree]","Init \u2713 \u2192 #"+a)}else TnetLog.error("[LM-Tree]","TnetLMStore nicht geladen")}else TnetLog.error("[LM-Tree]","Container #"+a+" nicht gefunden")},destroy:function(){u&&("function"==typeof cancelAnimationFrame?cancelAnimationFrame(u):
clearTimeout(u),u=null);Object.keys(p).forEach(function(a){clearTimeout(p[a])});p={};t.forEach(function(a){a()});t=[];h&&(h.innerHTML="")},render:function(a){if(h&&a&&a.length){r||=a[0].id;x={};y="";var d='<div class="lm-tab-bar">';for(var b=0;b<a.length;b++){var c=a[b],e=C[c.id]||{label:c.name.substring(0,2).toUpperCase()},f=D[c.id]||c.alias||c.name;d+='<div class="lm-tab'+(c.id===r?" lm-tab-active":"")+'" data-cat-id="'+l(c.id)+'" title="'+l(f)+'">';e.wappen?d+='<img class="lm-tab-icon" src="'+
l(e.wappen)+'" alt="'+l(f)+'" title="'+l(f)+'">':d+='<span class="lm-tab-label" title="'+l(f)+'">'+l(e.label)+"</span>";d+="</div>"}d+='</div><div class="lm-search-wrap"><input type="text" class="lm-search" placeholder="Thema suchen\u2026"><span class="lm-search-clear" style="display:none">&times;</span></div>';for(b=0;b<a.length;b++)c=a[b],e=c.id===r,d+='<div class="lm-cat-content" data-cat-content="'+l(c.id)+'"',d+=e?">":' style="display:none">',e&&(d+=this._renderCategory(c),x[c.id]=!0),d+="</div>";
h.innerHTML=d+'<div class="lm-no-results" style="display:none">Keine Themen gefunden</div>';this._bindEvents();this._resyncLayerCheckboxes();document.dispatchEvent(new CustomEvent("lm-catalog-rendered",{bubbles:!1}))}},_renderCategory:function(a){a=a.subcategories||[];for(var d="",b=0;b<a.length;b++)d+=this._renderSubcategory(a[b]);return d},_renderSubcategory:function(a){var d=a.groups||[];if(a.hideHeader){a="";for(var b=0;b<d.length;b++)a+=this._renderGroup(d[b],1);return a}b=this._clampDepth(1);
var c=this._countLeaves(d),e=!1!==a.expanded?" lm-expanded":" lm-collapsed",f=!0===a.locked||!0===a.accessDenied||this._allLocked(d);e='<div class="lm-subcat'+e+(f?" lm-group-locked":"")+'" data-group-id="'+l(a.id)+'"'+(f?' data-locked="1"':"")+">";e+='<div class="lm-subcat-header lm-depth-'+b+'" data-action="toggle-group" data-lm-depth="'+b+'"><span class="lm-arrow">\u25b6</span>';f&&(e+='<span class="lm-cb lm-cb-locked" title="Kein Zugriff \u2013 berechtigtes Login n\u00f6tig" style="display:inline-flex;align-items:center;justify-content:center;width:16px;height:16px;opacity:.6">'+
w()+"</span>");e+='<span class="lm-subcat-name"'+(f?' style="opacity:.6"':"")+">"+l(a.name)+"</span>";e+='<span class="lm-count">'+c+"</span>";e+="</div>";e+='<div class="lm-subcat-body">';for(a=0;a<d.length;a++)e+=this._renderGroup(d[a],2);return e+="</div>",e+="</div>",e},_renderGroup:function(a,d){d=this._clampDepth(d);var b=a.layers||[];if(a.hideHeader&&1===b.length&&"group"!==b[0].type)return this._renderLeafLayer(b[0],d);var c=this._countLeaves(b),e=!0===a.open||!0===a.expanded?" lm-expanded":
" lm-collapsed",f=!0===a.locked||!0===a.accessDenied||this._allLocked(b),g=!0===a.selectAll&&!f,k=a.legend&&""!==a.legend;e='<div class="lm-group'+e+" lm-depth-"+d+(f?" lm-group-locked":"")+'" data-group-id="'+l(a.id)+'" data-lm-depth="'+d+'"'+(f?' data-locked="1"':"")+">";e+='<div class="lm-group-header lm-depth-'+d+'" data-action="toggle-group" data-lm-depth="'+d+'"><span class="lm-arrow">\u25b6</span>';f?e+='<span class="lm-cb lm-cb-locked" title="Kein Zugriff \u2013 berechtigtes Login n\u00f6tig" style="display:inline-flex;align-items:center;justify-content:center;width:16px;height:16px;opacity:.6">'+
w()+"</span>":g&&(e+='<input type="checkbox" class="lm-group-cb" data-action="select-all" data-group-id="'+l(a.id)+'" title="Alle Layer ein-/ausschalten">');e+='<span class="lm-group-name"'+(f?' style="opacity:.6"':"")+">"+l(a.name)+"</span>";k&&(e+='<button class="lm-legend-btn" data-action="open-legend" data-legend-key="'+l(a.legend)+'"',a.legendLink&&(e+=' data-legend-link="'+l(a.legendLink)+'"'),a.legendTitle&&(e+=' data-legend-title="'+l(a.legendTitle)+'"'),e+=' title="Legende anzeigen">'+z()+
"</button>");e+='<span class="lm-count">'+c+"</span>";e+="</div>";e+='<div class="lm-group-body">';for(a=0;a<b.length;a++)e+=this._renderLayerItem(b[a],d+1);return e+="</div>",e+="</div>",e},_renderLayerItem:function(a,d){d=this._clampDepth(d);if("group"===a.type&&a.layers&&a.layers.length){var b=this._countLeaves(a.layers),c=!0===a.open||!0===a.expanded?" lm-expanded":" lm-collapsed",e=!0===a.locked||!0===a.accessDenied||this._allLocked(a.layers),f=!0===a.selectAll&&!e,g=a.legend&&""!==a.legend;
c='<div class="lm-nested-group'+c+" lm-depth-"+d+(e?" lm-group-locked":"")+'" data-group-id="'+l(a.id)+'" data-lm-depth="'+d+'"'+(e?' data-locked="1"':"")+">";c+='<div class="lm-nested-header lm-depth-'+d+'" data-action="toggle-group" data-lm-depth="'+d+'"><span class="lm-arrow">\u25b6</span>';e?c+='<span class="lm-cb lm-cb-locked" title="Kein Zugriff \u2013 berechtigtes Login n\u00f6tig" style="display:inline-flex;align-items:center;justify-content:center;width:16px;height:16px;opacity:.6">'+w()+
"</span>":f&&(c+='<input type="checkbox" class="lm-group-cb" data-action="select-all" data-group-id="'+l(a.id)+'" title="Alle Layer ein-/ausschalten">');c+='<span class="lm-nested-name"'+(e?' style="opacity:.6"':"")+">"+l(a.name)+"</span>";g&&(c+='<button class="lm-legend-btn" data-action="open-legend" data-legend-key="'+l(a.legend)+'"',a.legendLink&&(c+=' data-legend-link="'+l(a.legendLink)+'"'),a.legendTitle&&(c+=' data-legend-title="'+l(a.legendTitle)+'"'),c+=' title="Legende anzeigen">'+z()+"</button>");
c+='<span class="lm-count">'+b+"</span>";c+="</div>";c+='<div class="lm-nested-body">';for(b=0;b<a.layers.length;b++)c+=this._renderLayerItem(a.layers[b],d+1);return c+="</div>",c+="</div>",c}return this._renderLeafLayer(a,d)},_renderLeafLayer:function(a,d){var b=this._clampDepth(d),c=!0===a.locked||!0===a.accessDenied,e=a.visible?" checked":"",f=a.visible?" lm-active":"",g=a.legend&&""!==a.legend,k=a._missing?" lm-layer--missing":"",m=a._missing?' data-missing="1"':"",n="";a.loading&&(n+=" lm-layer-loading");
a.loadingSlow&&(n+=" lm-layer-slow");a.loadingError&&(n+=" lm-layer-error");d="";if(d+='<div class="lm-layer lm-depth-'+b+f+k+n+(c?" lm-layer-locked":"")+'" data-layer-id="'+l(a.id)+'" data-lm-depth="'+b+'"'+m+(c?' data-locked="1"':"")+' data-name="'+l((a.name||"").toLowerCase())+'">',d+='<label class="lm-layer-label"'+(c?' style="cursor:not-allowed"':"")+">",d+='<span class="lm-cb-wrap">',c?d+='<span class="lm-cb lm-cb-locked" title="Kein Zugriff \u2013 berechtigtes Login n\u00f6tig" style="display:inline-flex;align-items:center;justify-content:center;width:16px;height:16px;opacity:.6">'+
w()+"</span>":d+='<input type="checkbox" class="lm-cb"'+e+' data-action="toggle-layer">',d+="</span>",d+='<span class="lm-layer-name"'+(c?' style="opacity:.6"':"")+">"+l(a.name)+"</span>",a._missing&&(d+='<span class="lm-layer-missing-badge" title="Keine Layer-Definition in der Datenbank">\u26a0 fehlt</span>'),d+="</label>",g)b=a.legendLayers||"",d+='<button class="lm-legend-btn" data-action="open-legend" data-legend-key="'+l(a.legend)+'"',b&&(d+=' data-legend-layers="'+l(b)+'"'),a.legendLink&&(d+=
' data-legend-link="'+l(a.legendLink)+'"'),a.legendTitle&&(d+=' data-legend-title="'+l(a.legendTitle)+'"'),d+=' title="Legende anzeigen">'+z()+"</button>";return d+="</div>",d},_bindEvents:function(){if(!h.__tnetLmTreeBound){h.__tnetLmTreeBound=!0;var a=this;h.addEventListener("click",function(b){var c=b.target.closest(".lm-tab");if(c)(c=c.dataset.catId)&&c!==r&&a._switchTab(c);else if(c=b.target.closest('[data-action="open-legend"]'))b.stopPropagation(),a._openLegend(c.dataset.legendKey,c.dataset.legendLayers||
"",c.dataset.legendLink||"",c.dataset.legendTitle||"");else if(b.target.matches('[data-action="select-all"]'))b.stopPropagation();else{var e=b.target.closest('[data-action="toggle-group"]');if(e){var f=e.closest(".lm-subcat, .lm-group, .lm-nested-group");if(f)if(b.preventDefault(),c=f.classList.contains("lm-collapsed"),b.ctrlKey||b.metaKey){if(b=e.getAttribute("data-lm-depth"),(f=f.parentElement)&&b){f=f.querySelectorAll(':scope > .lm-subcat,:scope > .lm-group[data-lm-depth="'+b+'"],:scope > .lm-nested-group[data-lm-depth="'+
b+'"]');for(e=0;e<f.length;e++)c?(f[e].classList.add("lm-expanded"),f[e].classList.remove("lm-collapsed")):(f[e].classList.remove("lm-expanded"),f[e].classList.add("lm-collapsed"));TnetLog.debug("[LM-Tree]","Ctrl+Klick: Tiefe",b,"\u2192",f.length,"Knoten",c?"ge\u00f6ffnet":"geschlossen")}}else c?(f.classList.add("lm-expanded"),f.classList.remove("lm-collapsed")):(f.classList.remove("lm-expanded"),f.classList.add("lm-collapsed")),TnetLog.debug("[LM-Tree]","Toggle:",f.dataset.groupId,c?"\u2192 offen":
"\u2192 geschlossen","classes:",f.className.substring(0,60));else TnetLog.warn("[LM-Tree]","Toggle: kein Gruppen-Element gefunden f\u00fcr",e)}else b.target.closest(".lm-search-clear")&&((c=h.querySelector(".lm-search"))&&(c.value="",c.focus()),a._applyFilter(""))}});h.addEventListener("change",function(b){if(b.target.matches('[data-action="toggle-layer"]')){if(b=b.target.closest(".lm-layer")){b=b.dataset.layerId;var c=window.TnetLMStore;"function"==typeof c.isLayerActive&&c.isLayerActive(b)?("function"==
typeof c.isLayerRequestedVisible?c.isLayerRequestedVisible(b):1)?"function"==typeof c.setLayerEye?c.setLayerEye(b,!1):c.toggleLayer(b):"function"==typeof c.removeLayer?c.removeLayer(b):c.toggleLayer(b):c.toggleLayer(b)}}else if(b.target.matches('[data-action="select-all"]')){var e=b.target.dataset.groupId,f=b.target.checked;e&&window.TnetLMStore&&(window.TnetLMStore.setGroupAllVisible(e,f),setTimeout(function(){a._syncGroupCheckboxes(e,f)},1200))}});var d=h.querySelector(".lm-search");d&&d.addEventListener("input",
function(){clearTimeout(B);var b=d.value;B=setTimeout(function(){a._applyFilter(b)},200)})}},_switchTab:function(a){r=a;for(var d=h.querySelectorAll(".lm-tab"),b=0;b<d.length;b++)d[b].classList.toggle("lm-tab-active",d[b].dataset.catId===a);d=h.querySelectorAll(".lm-cat-content");for(b=0;b<d.length;b++){var c=d[b].dataset.catContent===a;if(d[b].style.display=c?"":"none",c&&!x[a]){c=(c=window.TnetLMStore)?c.getCatalog():[];for(var e=0;e<c.length;e++)if(c[e].id===a){d[b].innerHTML=this._renderCategory(c[e]);
x[a]=!0;break}}}this._resyncLayerCheckboxes();y&&this._applyFilter(y)},_applyFilter:function(a){y=a;var d=(a||"").trim().toLowerCase();a=h.querySelector(".lm-search-clear");var b=h.querySelector(".lm-search-wrap");a&&(a.style.display=d?"":"none");b&&b.classList.toggle("lm-search-active",!!d);if(a=h.querySelector('.lm-cat-content[data-cat-content="'+r+'"]')){var c=a.querySelectorAll(".lm-layer");a=a.querySelectorAll(".lm-subcat, .lm-group, .lm-nested-group");if(!d||2>d.length){for(b=0;b<c.length;b++)c[b].style.display=
"",c[b].classList.remove("lm-filter-match");for(b=0;b<a.length;b++)a[b].style.display="",a[b].classList.contains("lm-filter-open")&&(a[b].classList.remove("lm-filter-open"),"collapsed"===a[b].dataset.preFilterState&&(a[b].classList.remove("lm-expanded"),a[b].classList.add("lm-collapsed")),delete a[b].dataset.preFilterState);(a=h.querySelector(".lm-no-results"))&&(a.style.display="none")}else{for(var e=b=0;e<c.length;e++){var f=c[e],g=-1!==(f.dataset.name||"").indexOf(d);f.style.display=g?"":"none";
f.classList.toggle("lm-filter-match",g);g&&b++}for(d=a.length-1;0<=d;d--)if(c=a[d],f=c.querySelector(".lm-subcat-body, .lm-group-body, .lm-nested-body")){e=!1;g=f.querySelectorAll(":scope > .lm-layer");for(var k=0;k<g.length;k++)if("none"!==g[k].style.display){e=!0;break}if(!e)for(f=f.querySelectorAll(":scope > .lm-group, :scope > .lm-nested-group"),g=0;g<f.length;g++)if("none"!==f[g].style.display){e=!0;break}c.style.display=e?"":"none";e&&!c.classList.contains("lm-filter-open")&&(c.dataset.preFilterState||
(c.dataset.preFilterState=c.classList.contains("lm-collapsed")?"collapsed":"expanded"),c.classList.add("lm-expanded","lm-filter-open"),c.classList.remove("lm-collapsed"))}else c.style.display="none";(a=h.querySelector(".lm-no-results"))&&(a.style.display=0===b?"":"none")}}},_onLayerVisibility:function(a){if(h){var d=this,b=window.TnetLMStore;b=b&&"function"==typeof b.isLayerActive?b.isLayerActive(a.id):a.visible;for(var c=h.querySelectorAll('[data-layer-id="'+a.id+'"]'),e=0;e<c.length;e++){var f=
c[e].querySelector(".lm-cb");f&&(f.checked=b);c[e].classList.toggle("lm-active",b);c[e].classList.toggle("lm-layer-hidden",b&&!a.visible);a.visible?(c[e].classList.add("lm-layer-loading","lm-layer-loading-hint"),c[e].classList.remove("lm-layer-error")):c[e].classList.remove("lm-layer-loading","lm-layer-loading-hint","lm-layer-loading-real","lm-layer-slow","lm-layer-error")}p[a.id]&&(clearTimeout(p[a.id]),delete p[a.id]);a.visible&&(p[a.id]=setTimeout(function(){delete p[a.id];for(var g=h?h.querySelectorAll('[data-layer-id="'+
a.id+'"]'):[],k=0;k<g.length;k++)g[k].classList.remove("lm-layer-loading-hint"),g[k].classList.contains("lm-layer-loading-real")||g[k].classList.remove("lm-layer-loading");d._updateSelectAllCheckboxes()},1400));this._updateSelectAllCheckboxes()}},_onLayerLoading:function(a){if(h&&a&&a.id){var d=a.state||{},b=!(!d.loading&&!d.loadingSlow),c=!!d.loadingError,e=h.querySelectorAll('[data-layer-id="'+a.id+'"]');p[a.id]&&(clearTimeout(p[a.id]),delete p[a.id]);for(a=0;a<e.length;a++){var f=e[a],g=f.querySelector(".lm-layer-status");
g&&g.remove();f.classList.toggle("lm-layer-slow",!!d.loadingSlow);f.classList.toggle("lm-layer-error",!b&&c);b?(f.classList.add("lm-layer-loading","lm-layer-loading-real"),f.classList.remove("lm-layer-loading-hint")):(f.classList.remove("lm-layer-loading-real","lm-layer-loading-hint"),f.classList.remove("lm-layer-loading"))}}},_onActiveLayersChanged:function(){if(!u){var a=this,d=function(){u=null;a._resyncLayerCheckboxes()};u="function"==typeof requestAnimationFrame?requestAnimationFrame(d):setTimeout(d,
16);window.__tnetActiveBookmark||setTimeout(function(){a._resyncLayerCheckboxes()},800)}},_onGroupToggled:function(a){if(h)for(var d=h.querySelectorAll('[data-group-id="'+a.id+'"]'),b=0;b<d.length;b++)d[b].classList.toggle("lm-expanded",a.expanded),d[b].classList.toggle("lm-collapsed",!a.expanded)},_updateSelectAllCheckboxes:function(){if(h){var a=window.TnetLMStore;if(a&&"function"==typeof a.getGroupVisibilityState)for(var d=h.querySelectorAll('.lm-group-cb[data-action="select-all"]'),b=0;b<d.length;b++){var c=
d[b].dataset.groupId;if(c){c=a.getGroupVisibilityState(c);d[b].checked="all"===c;d[b].indeterminate="partial"===c;var e=d[b].closest("[data-group-id]");e&&e.classList.toggle("lm-partial","partial"===c)}}}},_resyncLayerCheckboxes:function(){if(h){var a=window.TnetLMStore;if(a){var d="function"==typeof a.isLayerActive?a.isLayerActive.bind(a):null;a="function"==typeof a.isLayerRequestedVisible?a.isLayerRequestedVisible.bind(a):"function"==typeof a.isLayerEffectivelyVisible?a.isLayerEffectivelyVisible.bind(a):
null;if(d||a){for(var b=h.querySelectorAll(".lm-layer[data-layer-id]"),c=0;c<b.length;c++){var e=b[c].dataset.layerId;if(e){var f=a?a(e):!1;e=d?d(e):f;var g=b[c].querySelector(".lm-cb");g&&(g.checked=e);b[c].classList.toggle("lm-active",e);b[c].classList.toggle("lm-layer-hidden",e&&!f)}}this._updateSelectAllCheckboxes()}}}},_syncToActiveBookmark:function(){var a=window.__tnetActiveBookmark;if(a&&h&&!a.themes){a=Array.isArray(a.layers)?a.layers:[];for(var d=null,b=0;b<a.length;b++)if(a[b]&&a[b].id&&
!1!==a[b].visible){d=a[b].id;break}!d&&a.length&&a[0]&&a[0].id&&(d=a[0].id);d&&this.navigateToLayer(d)}},_initResolutionWatch:function(){function a(){var b="u">typeof njs&&njs.AppManager&&njs.AppManager.Maps&&njs.AppManager.Maps.main;if(b=b&&b.mapObj){var c=b.getView();if(c){var e=null;c.on("change:resolution",function(){clearTimeout(e);e=setTimeout(function(){d._updateOutOfRange(c.getResolution())},200)});d._updateOutOfRange(c.getResolution());TnetLog.log("[LM-Tree]","Resolution-Watch aktiv")}}else setTimeout(a,
2E3)}var d=this;a()},_updateOutOfRange:function(a){if(h){var d=window.TnetLMStore;if(d)for(var b=h.querySelectorAll(".lm-layer[data-layer-id]"),c=0;c<b.length;c++){var e=d.findLayer(b[c].dataset.layerId);if(e){var f=e.maxResolution,g=e.minResolution;if(e._olLayerRef){var k=e._olLayerRef.getMaxResolution();e=e._olLayerRef.getMinResolution();k&&k!==1/0&&(f=k);e&&0<e&&(g=e)}k=!1;f&&a>f&&(k=!0);g&&a<g&&(k=!0);b[c].classList.toggle("lm-out-of-range",k)}}}},_syncGroupCheckboxes:function(a,d){if(h){var b=
h.querySelector('[data-group-id="'+a+'"]');if(b){b=b.querySelectorAll(".lm-layer");var c=window.TnetLMStore;c=c&&"function"==typeof c.isLayerRequestedVisible?c.isLayerRequestedVisible.bind(c):c&&"function"==typeof c.isLayerEffectivelyVisible?c.isLayerEffectivelyVisible.bind(c):null;for(var e=0,f=0;f<b.length;f++){var g=b[f].querySelector(".lm-cb");if(g&&g.checked!==d){var k=b[f].dataset.layerId;c&&c(k)===d&&(g.checked=d,b[f].classList.toggle("lm-active",d),e++)}}0<e&&TnetLog.log("[LMTree]","_syncGroupCheckboxes:",
e,"Checkboxen korrigiert f\u00fcr",a);this._updateSelectAllCheckboxes()}}},_openLegend:function(a,d,b,c){if(a){var e;b?e=b:(e=v()+"/tnet/api/v1/legend-proxy.php?service="+encodeURIComponent(a),d&&(e+="&layers="+encodeURIComponent(d)));(window.__TNET_LEGEND_CONFIG||{}).metadata&&-1!==e.indexOf("legend-proxy")&&-1===e.indexOf("metadata=")&&(e+=(-1!==e.indexOf("?")?"&":"?")+"metadata=1");a=c||a.split("/").pop()||"Legende";(d=window.njs&&window.njs.AppManager)||(d=window.top&&window.top.njs&&window.top.njs.AppManager);
d&&"function"==typeof d.showLegend?(d.showLegend(e,a,!0,void 0),TnetLog.log("[LM-Tree]","Legende ge\u00f6ffnet:",e)):window.open(e,"_blank","noopener")}},_countLeaves:function(a){for(var d=0,b=0;b<a.length;b++){var c=a[b],e=c.layers||c.groups;e&&e.length?d+=this._countLeaves(e):"group"!==c.type&&d++}return d},_allLocked:function(a){for(var d=!1,b=0;b<(a||[]).length;b++){var c=a[b],e=c.layers||c.groups;if(e&&e.length){if(!this._allLocked(e))return!1;d=!0}else if("group"!==c.type&&(d=!0,!0!==c.locked&&
!0!==c.accessDenied))return!1}return d},_clampDepth:function(a){a=parseInt(a,10);return!isFinite(a)||1>a?1:6<a?6:a},navigateToLayer:function(a,d){function b(){var g=h.querySelector('[data-layer-id="'+a+'"]')||h.querySelector('[data-group-id="'+a+'"]');if(!g&&5>f)f++,setTimeout(b,150);else{if(!g){for(var k=a.split("/");!g&&1<k.length;){k.pop();var m=k.join("/");g=h.querySelector('[data-layer-id="'+m+'"]')||h.querySelector('[data-group-id="'+m+'"]')}if(!g){TnetLog.warn("[LM-Tree]","navigateToLayer: Layer nicht im DOM gefunden:",
a);return}TnetLog.log("[LM-Tree]","navigateToLayer: Eltern-Element gefunden:",k.join("/"),"(statt:",a,")")}k=function(q){q&&q.classList&&(q.classList.contains("lm-subcat")||q.classList.contains("lm-group")||q.classList.contains("lm-nested-group"))&&(q.classList.add("lm-expanded"),q.classList.remove("lm-collapsed"))};k(g);for(m=g.parentElement;m&&m!==h;)k(m),m=m.parentElement;var n=function(){g.scrollIntoView({behavior:"smooth",block:"center"});g.classList.remove("lm-highlight");g.offsetWidth;g.classList.add("lm-highlight");
setTimeout(function(){g.classList.remove("lm-highlight")},2500)};"function"==typeof requestAnimationFrame?requestAnimationFrame(function(){requestAnimationFrame(n)}):setTimeout(n,60)}}if(!h||!a)return!1;var c=window.TnetLMStore;if(!c)return!1;d=d||null;if(!d){c=c.getCatalog();for(var e=0;e<c.length;e++)if(this._catalogNodeContainsLayer(c[e],a)){d=c[e].id;break}}d&&d!==r&&this._switchTab(d);var f=0;return setTimeout(b,80),!0},_catalogNodeContainsLayer:function(a,d){if(a.id===d)return!0;a=a.subcategories||
a.groups||a.layers||[];for(var b=0;b<a.length;b++)if(this._catalogNodeContainsLayer(a[b],d))return!0;return!1},navigateToSubcategory:function(a,d){function b(){var g=h;if(d){var k=h.querySelector('[data-cat-content="'+d+'"]');k&&(g=k)}k=g.querySelector('.lm-subcat[data-group-id="'+e+'"]');if(!k){g=g.querySelectorAll(".lm-subcat-name");for(var m=0;m<g.length;m++)if(g[m].textContent.trim().toLowerCase()===e){var n=g[m].closest(".lm-subcat");if(n){k=n;break}}}return k}function c(){var g=b();!g&&5>f?
(f++,setTimeout(c,150)):g?(g.classList.add("lm-expanded"),g.classList.remove("lm-collapsed"),(g.querySelector(".lm-subcat-header")||g).scrollIntoView({behavior:"smooth",block:"start"}),g.classList.add("lm-highlight"),setTimeout(function(){g.classList.remove("lm-highlight")},2500),TnetLog.log("[LM-Tree]","navigateToSubcategory:",a,"\u2192",g.dataset.groupId)):TnetLog.warn("[LM-Tree]","navigateToSubcategory: nicht gefunden:",a,"(Kategorie:",d||"alle",")")}if(!h||!a||!window.TnetLMStore)return!1;var e=
a.trim().toLowerCase();d&&d!==r&&this._switchTab(d);var f=0;return setTimeout(c,80),!0},expandThemes:function(a){if(a&&h){var d=this,b={ow:"obwalden",nw:"nidwalden",ch:"bund",we:"weitere"},c=window.__tnetActiveBookmark;c=!(!c||!Array.isArray(c.layers));var e=document.getElementById("tp_overview_menu");!c&&e&&!e.open&&(e.open=!0);a=a.split(",");for(c=0;c<a.length;c++)if(e=a[c].trim()){var f=null,g=e,k=e.indexOf(":");if(0<k&&3>=k){var m=e.substring(0,k).toLowerCase();b[m]&&(f=b[m],g=e.substring(k+1).trim())}(function(n,
q,E){setTimeout(function(){d.navigateToSubcategory(n,q)},E)})(g,f,300*c)}}}}})();
