var __tnetInitialUrlLayers=null,__tnetInitialUrlOp=null,__tnetInitialUrlQuery="",__tnetBookmarkAutoStartStarted=!1,__tnetInitialUrlLayerCount=0,__tnetInitialUrlGuardUntil=Date.now()+18E3;
try{__tnetInitialUrlQuery=window.location.search||"";var __tnetInitialUrlParams=new URLSearchParams(window.location.search);__tnetInitialUrlLayers=__tnetInitialUrlParams.get("layers");__tnetInitialUrlOp=__tnetInitialUrlParams.get("op");__tnetInitialUrlLayerCount=__tnetInitialUrlLayers?__tnetInitialUrlLayers.split("|").filter(function(c){return!!c}).length:0}catch{}
__tnetInitialUrlOp&&!window.__tnetInitialOpHistoryGuardInstalled&&function(){function c(e){if(null==e)return e;try{var f=new URL(String(e),window.location.href),a=f.searchParams,g=a.get("layers")||"";g&&g.split("|").filter(function(l){return!!l});var p=__tnetInitialUrlOp.split("|").filter(function(l){return""!==l}).length;return window.__tnetInitialOpHistoryGuardEnabled&&Date.now()<__tnetInitialUrlGuardUntil&&(__tnetInitialUrlLayers&&__tnetInitialUrlLayerCount&&a.set("layers",__tnetInitialUrlLayers),
__tnetInitialUrlOp&&p===__tnetInitialUrlLayerCount&&a.set("op",__tnetInitialUrlOp)),f.pathname+(a.toString()?"?"+a.toString():"")+f.hash}catch{return e}}var d=window.history;if(d&&"function"==typeof d.replaceState){var h=d.replaceState,b=d.pushState;window.__tnetInitialOpHistoryGuardInstalled=!0;window.__tnetInitialOpHistoryGuardEnabled=!0;d.replaceState=function(e,f,a){a=c(a);if(a!==window.location.pathname+window.location.search+window.location.hash)return h.call(this,e,f,a)};"function"==typeof b&&
(d.pushState=function(e,f,a){a=c(a);if(a!==window.location.pathname+window.location.search+window.location.hash)return b.call(this,e,f,a)})}}();
__tnetInitialUrlOp&&!window.__tnetInitialOpStabilizerInstalled&&function(){function c(){try{var b=new URL(window.location.href),e=b.searchParams.get("layers")||"";e&&e.split("|").filter(function(a){return!!a});var f=b.searchParams.get("op")||"";if(Date.now()>=h||Date.now()>=__tnetInitialUrlGuardUntil||!window.__tnetInitialOpHistoryGuardEnabled)return;if(__tnetInitialUrlLayers&&b.searchParams.get("layers")!==__tnetInitialUrlLayers&&b.searchParams.set("layers",__tnetInitialUrlLayers),__tnetInitialUrlOp&&
f!==__tnetInitialUrlOp){b.searchParams.set("op",__tnetInitialUrlOp);d.replaceState(null,"",b.pathname+"?"+b.searchParams.toString()+b.hash);return}__tnetInitialUrlLayers&&b.searchParams.get("layers")!==__tnetInitialUrlLayers&&d.replaceState(null,"",b.pathname+"?"+b.searchParams.toString()+b.hash)}catch{return}"function"==typeof window.requestAnimationFrame?window.requestAnimationFrame(c):setTimeout(c,16)}var d=window.history;if(d&&"function"==typeof d.replaceState){window.__tnetInitialOpStabilizerInstalled=
!0;var h=Date.now()+2E4;c()}}();
function initPanelShadow(){function c(){var a=document.getElementById("spring");if(a){var g=a.querySelectorAll(":scope > .dijitTitlePane");g=0<g.length?g[g.length-1].getBoundingClientRect().bottom+10:h.getBoundingClientRect().bottom}else g=h.getBoundingClientRect().bottom;a=69+(a?a.scrollHeight:400)+10;g>a&&(g=a);a=h.offsetWidth||340;b.style.top="69px";b.style.height=g-69+"px";b.style.width=a+"px";d.classList.contains("close")?(b.style.width="170px",b.style.left="85px",b.style.borderRadius="0 0 4px 4px"):
(b.style.left="0px",b.style.borderRadius="0 0 4px 4px")}var d=document.getElementById("freepane"),h=document.querySelector(".close_switch");if(d&&h){var b=document.createElement("div");b.id="panelShadow";d.parentNode.insertBefore(b,d.nextSibling);c();var e=document.getElementById("spring");if("u">typeof ResizeObserver){var f=new ResizeObserver(c);f.observe(d);f.observe(h);e&&f.observe(e)}(new MutationObserver(c)).observe(d,{attributes:!0,attributeFilter:["class"]});e&&(new MutationObserver(c)).observe(e,
{childList:!0,subtree:!0,attributes:!0,attributeFilter:["class","style"]});document.addEventListener("tnet-app-ready",function(){setTimeout(c,100);setTimeout(c,500)});window.addEventListener("resize",c)}else setTimeout(initPanelShadow,200)}"loading"===document.readyState?document.addEventListener("DOMContentLoaded",initPanelShadow):initPanelShadow();function scrollSpringToTop(){var c=document.getElementById("spring");c&&c.scrollTo({top:0,behavior:"smooth"})}
function initScrollToTop(){var c=document.getElementById("spring"),d=document.getElementById("scrollToTopBtn");c&&d?c.addEventListener("scroll",function(){100<c.scrollTop?d.classList.add("visible"):d.classList.remove("visible")}):setTimeout(initScrollToTop,500)}"loading"===document.readyState?document.addEventListener("DOMContentLoaded",initScrollToTop):initScrollToTop();
function startBookmarkFromUrl(){var c=window.location.pathname.match(/\/maps(?:-dev)?\/([a-zA-Z0-9_-]+)$/);if(c&&c[1]){let p=function(){try{var m=window.njs&&window.njs.AppManager,k=m&&m.LyrMgr,n=window.dijit&&"function"==typeof window.dijit.byId?window.dijit.byId("main_lyrmgr"):null;return k&&k.main_lyrmgr&&"function"==typeof k.main_lyrmgr.switchLayersProgr?n&&n.domNode&&n.domNode.childNodes&&n.domNode.childNodes.length?!0:1<=Object.keys(k).length:!1}catch{return!1}},l=function(){if("function"==
typeof window.TnetSetBookmark&&window.njs&&window.njs.AppManager&&"function"==typeof window.njs.AppManager.setMapBookmark&&p()){var m=b&&/[?&](lang|basemap|blop|x|y|zl|hl|theme|subtheme|layers|op|view)=/.test(b)?{visibleLayerIds:e?e.split("|").filter(function(k){return!!k}):null,originalVisibleLayerIds:e?e.split("|").filter(function(k){return!!k}):null,opacityValues:f?f.split("|"):null,originalOp:f||"",urlQuery:b,urlOverride:!0}:null;window.TnetSetBookmark(d,h,m)}else setTimeout(l,200)};if(!__tnetBookmarkAutoStartStarted){__tnetBookmarkAutoStartStarted=
!0;var d=c[1],h=null,b=__tnetInitialUrlQuery||window.__tnetOriginalUrlQuery||"",e=__tnetInitialUrlLayers||window.__tnetOriginalUrlLayers||null,f=__tnetInitialUrlOp||window.__tnetOriginalUrlOp||null;try{var a=new URLSearchParams(window.location.search),g=a.get("view");g&&/^[a-zA-Z0-9_-]+$/.test(g)&&(h=g);e||=a.get("layers");f||=a.get("op")}catch{}l()}}}window._tnetAppReadyFired?startBookmarkFromUrl():document.addEventListener("tnet-app-ready",function(){startBookmarkFromUrl()},{once:!0});
setTimeout(startBookmarkFromUrl,1500);setTimeout(startBookmarkFromUrl,3500);setTimeout(startBookmarkFromUrl,7E3);
