(function(){function t(){function a(d){return d>=c.length?Promise.resolve(null):fetch(c[d]).then(function(e){if(!e.ok)throw Error(e.status);return e.text()}).then(function(e){return JSON5.parse(e)}).catch(function(){return a(d+1)})}if("u"<typeof JSON5)return TnetLog.warn("[LM-Init]","JSON5 nicht verf\u00fcgbar"),Promise.resolve(null);var b=window.__TNET_APP_ROOT||"/maps",c=[b+"/tnet/config/tnet-global-config.json5",b+"/tnet/tnet-global-config.json5","../tnet/config/tnet-global-config.json5"];return a(0)}
function v(){if(TnetLog.log("[LM-Init]","hideLegacyContainers \u2014 Desktop="+f+", useNewActivePanel="+g+", useNewTree="+h+", useNewWmsPanel="+m),g&&(n("njs_main_lyrsorter_wrapper"),f||n("sort_menu_sheet")),h)if(f){var a=document.getElementById("kantons_container");if(a){a=a.children;for(var b=0;b<a.length;b++)a[b].style.display="none";TnetLog.log("[LM-Init]","#kantons_container Kinder ausgeblendet ("+a.length+")")}}else n("kantons_container");m&&n("tp_wms_menu")}function n(a){var b=document.getElementById(a);
b&&(b.style.display="none",TnetLog.log("[LM-Init]","#"+a+" ausgeblendet"))}function p(a){(a=document.getElementById(a))&&(a.style.display="")}function r(a){TnetLog.warn("[LM-Init]","Fallback auf Legacy-Themenbaum:",a||"unbekannt");k&&(clearTimeout(k),k=null);(a=document.getElementById("lm-tree-container"))&&a.parentNode&&a.parentNode.removeChild(a);if(TnetLog.warn("[LM-Init]","Fallback: Legacy-Container werden wieder eingeblendet"),p("njs_main_lyrsorter_wrapper"),f||p("sort_menu_sheet"),f){if(a=document.getElementById("kantons_container")){a=
a.children;for(var b=0;b<a.length;b++)"lm-tree-container"!==a[b].id&&(a[b].style.display="")}}else p("kantons_container");p("tp_wms_menu")}function w(){var a=f?"lm-container lm-container-desktop":"lm-container";if(h&&!document.getElementById("lm-tree-container")){var b=document.createElement("div");if(b.id="lm-tree-container",b.className=a,f){var c=document.getElementById("kantons_container");c?(c.appendChild(b),TnetLog.log("[LM-Init]","[Desktop] #lm-tree-container in #kantons_container erstellt")):
(c=document.getElementById("tp_overview_menu"))?(c.appendChild(b),TnetLog.log("[LM-Init]","[Desktop] #lm-tree-container in #tp_overview_menu erstellt (Fallback)")):TnetLog.error("[LM-Init]","[Desktop] Weder #kantons_container noch #tp_overview_menu gefunden")}else if(c=document.querySelector("#m-layers-sheet .m-sheet-body")){var d=document.getElementById("kantons_container");d?c.insertBefore(b,d):c.appendChild(b);TnetLog.log("[LM-Init]","[Mobile] #lm-tree-container erstellt")}}g&&!document.getElementById("lm-active-container")&&
(f?(b=document.getElementById("sort_menu"))?(c=document.createElement("div"),c.id="lm-active-container",c.className=a,b.appendChild(c),TnetLog.log("[LM-Init]","[Desktop] #lm-active-container in #sort_menu erstellt")):TnetLog.error("[LM-Init]","[Desktop] #sort_menu nicht gefunden"):document.getElementById("lm-active-container")?TnetLog.log("[LM-Init]","[Mobile] #lm-active-container gefunden"):TnetLog.error("[LM-Init]","[Mobile] #lm-active-container nicht im HTML"))}function q(a){var b=a&&a.layerManager||
{};(window.__TNET_LEGEND_CONFIG=a&&a.legend||{},b.group)||(a=(new URLSearchParams(window.location.search)).get("group"))&&(b.group=a,TnetLog.log("[LM-Init]","Gruppe aus URL \u00fcbernommen: "+a));if(g=void 0!==b.useNewActivePanel?!!b.useNewActivePanel:!!b.useNew,h=!!b.useNewTree,m=!!b.useNewWmsPanel,TnetLog.log("[LM-Init]","Feature-Flags: useNewActivePanel="+g+", useNewTree="+h+", useNewWmsPanel="+m+", Plattform="+(f?"Desktop":"Mobile")),g||h||m)if(v(),w(),window.TnetLMStore){window.TnetLMStore.init(b);
h&&(window.TnetLMTree?(window.TnetLMTree.init("lm-tree-container"),TnetLog.log("[LM-Init]","TnetLMTree initialisiert"+(f?" (Desktop)":" (Mobile)"))):(TnetLog.warn("[LM-Init]","useNewTree=true, aber TnetLMTree Modul nicht geladen"),f||TnetLog.error("[LM-Init]","TnetLMTree fehlt auf Mobile \u2192 Fallback")));g&&(window.TnetLMActive?(window.__tnetConfig=window.__tnetConfig||{},window.__tnetConfig.layerManager=b,window.TnetLMActive.init("lm-active-container"),TnetLog.log("[LM-Init]","TnetLMActive initialisiert"+
(f?" (Desktop)":" (Mobile)"))):TnetLog.error("[LM-Init]","TnetLMActive nicht verfuegbar"));var c=window.TnetLMStore;c&&"function"==typeof c.on&&c.on("catalog-loaded",function(d){(k&&(clearTimeout(k),k=null),d&&d.length)?window.TnetCoalesceBridge&&window.TnetCoalesceBridge.isEnabled()&&window.TnetCoalesceBridge.restoreFromUrl(c):r("Katalog leer")});k=setTimeout(function(){var d=!(!c||"function"!=typeof c.isLoaded||!c.isLoaded()),e=!h;h&&(e=document.getElementById("lm-tree-container"),e=!!(e&&e.children&&
0<e.children.length));var l=!g;g&&(l=document.getElementById("lm-active-container"),l=!!(l&&l.children&&0<l.children.length));d&&e?TnetLog.log("[LM-Init]","Fallback-Timer: Alles ok (Store="+d+", Tree="+e+", Active="+l+")"):r("Timeout (6000ms) \u2014 Store geladen="+d+", Tree ok="+e+", Active ok="+l)},6E3)}else TnetLog.error("[LM-Init]","TnetLMStore fehlt"),r("TnetLMStore fehlt");else TnetLog.log("[LM-Init]","Alle Feature-Flags deaktiviert \u2192 Legacy-Modus")}function u(){t().then(function(a){if(a)if(window.njs&&
window.njs.AppManager&&window.njs.AppManager.Maps&&window.njs.AppManager.Maps.main)TnetLog.log("[LM-Init]","App bereits bereit \u2192 sofort starten"),q(a);else{var b=!1;document.addEventListener("tnet-app-ready",function(){b||(b=!0,q(a))});TnetLog.log("[LM-Init]","Warte auf tnet-app-ready...");var c=0,d=setInterval(function(){(c++,b)?clearInterval(d):window.njs&&window.njs.AppManager&&window.njs.AppManager.Maps&&window.njs.AppManager.Maps.main?(clearInterval(d),b||(b=!0,TnetLog.log("[LM-Init]","App bereit (Polling-Fallback nach "+
500*c+"ms) \u2192 starte"),q(a))):60<=c&&(clearInterval(d),TnetLog.warn("[LM-Init]","App nach 30s immer noch nicht bereit \u2192 Abbruch"))},500)}else TnetLog.warn("[LM-Init]","Config nicht geladen \u2192 Fallback-Verhalten")})}var f=!window.__TNET_MOBILE_ENTRY,k=null,g=!1,h=!1,m=!1;"loading"===document.readyState?document.addEventListener("DOMContentLoaded",u):u();window.TnetLMInit={reinit:function(){t().then(function(a){a&&q(a)})},getFlags:function(){return{useNewActivePanel:g,useNewTree:h,useNewWmsPanel:m,
isDesktop:f}}}})();
