(function(){function q(){return window.__TNET_APP_ROOT||"/maps"}function m(a,b,e){a=document.createElement(a);return b&&(a.className=b),e&&(a.innerHTML=e),a}function v(){var a=m("div","tnet-toc");a.id="tnetToc";var b=m("div","tnet-toc-header");b.innerHTML='<span class="tnet-toc-title">Karten</span><button class="tnet-toc-close" onclick="TnetTOC.close()">&times;</button>';a.appendChild(b);r.sections.forEach(function(e){a.appendChild(w(e))});document.body.appendChild(a);b=m("button","tnet-toc-toggle");
b.id="tnetTocToggle";b.innerHTML="<span>\u2630</span> Karten";b.onclick=function(){TnetTOC.toggle()};document.body.appendChild(b)}function w(a){var b=m("div","tnet-toc-section");b.dataset.sectionId=a.id;var e=m("div","tnet-toc-section-header");e.innerHTML='<img src="'+a.icon+'" alt=""><span>'+a.title+'</span><span class="tnet-toc-section-arrow">\u25b6</span>';e.onclick=function(){var g=a.id,c=document.querySelector('[data-section-id="'+g+'"]');c&&(c.classList.toggle("open"),n.sections[g]=c.classList.contains("open"))};
b.appendChild(e);var f=m("div","tnet-toc-items");return f.id="tnetTocItems_"+a.id,0===a.maps.length?f.innerHTML='<div class="tnet-toc-item" style="color:#999;font-style:italic;">Wird geladen...</div>':a.maps.forEach(function(g){f.appendChild(t(g))}),b.appendChild(f),b}function t(a){var b=m("div","tnet-toc-item");return b.textContent=a.title||a.name,b.dataset.mapId=a.id||a.name,b.onclick=function(){x(a)},b}function x(a){n.activeMap=a.id||a.name;document.querySelectorAll(".tnet-toc-item").forEach(function(e){e.classList.remove("active")});
var b=document.querySelector('[data-map-id="'+n.activeMap+'"]');b&&b.classList.add("active");"function"==typeof window.TnetSetBookmark?window.TnetSetBookmark(a.url||a.name):"function"==typeof window.reloadMap&&console.log("[TOC] Map selected:",a);600>=window.innerWidth&&TnetTOC.close()}function u(){y.init();z.init();console.log("[tnet_toc.js] Accordion/Tab-Konverter initialisiert")}if(window.__tnetLMFlags&&window.__tnetLMFlags.useNewTree)console.log("[tnet_toc.js] Neuer Layer-Manager-Tree aktiv \u2192 \u00fcbersprungen");
else{var y={getTabInfo:function(a,b){a=a.querySelectorAll('.dijitTabListWrapper [role="tab"]')[b];b={label:"Kategorie "+(b+1),iconClass:null};a&&(b.label=a.getAttribute("title")||a.textContent.trim()||b.label,a=a.querySelector(".dijitIcon, .dijitTabButtonIcon"))&&(a=Array.from(a.classList).filter(function(e){return-1!==e.indexOf("njsCategory")||-1!==e.indexOf("Icon")}),a.length&&(b.iconClass=a.join(" ")));return b},convert:function(a){var b=this;if("true"!==a.dataset.tabs2accDone){var e=a.querySelector(".dijitTabPaneWrapper");
if(e){var f=e.querySelectorAll(":scope > .dijitTabContainerTopChildWrapper");f.length&&(a.classList.add("tabs2acc-converted"),f.forEach(function(g,c){function h(){var l=d.classList.contains("is-open");d.classList.toggle("is-open",!l);g.classList.toggle("is-open",!l);g.style.display=l?"none":"block";d.setAttribute("aria-expanded",l?"false":"true")}if(!g.previousElementSibling||!g.previousElementSibling.classList.contains("tabs2acc-header")){c=b.getTabInfo(a,c);var d=document.createElement("div");d.className=
"tabs2acc-header";d.setAttribute("role","button");d.setAttribute("tabindex","0");d.setAttribute("aria-expanded","false");var k=document.createElement("span");if(k.className="acc-arrow",k.textContent="\u25b6",d.appendChild(k),c.iconClass)k=document.createElement("span"),k.className="acc-icon dijitIcon "+c.iconClass,d.appendChild(k);k=document.createElement("span");k.textContent=c.label;d.appendChild(k);g.classList.add("tabs2acc-panel");g.classList.remove("dijitVisible","dijitHidden");g.style.display=
"none";d.addEventListener("click",h);d.addEventListener("keydown",function(l){"Enter"!==l.key&&" "!==l.key||(l.preventDefault(),h())});e.insertBefore(d,g)}}),a.dataset.tabs2accDone="true")}}},processAll:function(){var a=this;document.querySelectorAll(".dijitTabContainer").forEach(function(b){a.convert(b)})},init:function(){function a(){e++;0<document.querySelectorAll(".dijitTabContainer").length&&b.processAll();30>e&&setTimeout(a,300)}var b=this,e=0;(a(),"u">typeof MutationObserver)&&(new MutationObserver(function(f){f.some(function(g){return 0<
g.addedNodes.length})&&b.processAll()})).observe(document.body,{childList:!0,subtree:!0})}},z={icons:{Nidwalden:q()+"/tnet/resources/wappen_nidwalden.svg",Obwalden:q()+"/tnet/resources/wappen_obwalden.svg",Bund:q()+"/tnet/resources/wappen_bund.svg",Weitere:q()+"/tnet/resources/icon_weitere.svg"},panes:[{id:"tp_layer_menu",name:"Nidwalden"},{id:"tp_layer_menu2",name:"Obwalden"},{id:"tp_layer_menu3",name:"Bund"},{id:"tp_layer_menu4",name:"Weitere"}],setPaneOpenSafe:function(a){if(a)try{a.set("open",
!0)}catch(b){TnetLog.warn("[tnet_toc.js] TitlePane konnte noch nicht geoeffnet werden:",b.message)}},convert:function(){function a(){if("u">typeof dijit&&"function"==typeof dijit.byId){var c=dijit.byId(b.panes[0].id);c&&(b.setPaneOpenSafe(c),setTimeout(function(){b.setPaneOpenSafe(c);c.resize&&c.resize()},200))}}var b=this,e=document.getElementById("kantons_container");if(!e||"true"===e.dataset.tabified||!this.panes.every(function(c){return document.getElementById(c.id)}))return!1;var f=document.createElement("div");
f.id="kantons_tab_bar";this.panes.forEach(function(c,h){var d=document.createElement("div");if(d.className="kanton-tab"+(0===h?" active":""),d.dataset.target=c.id,b.icons[c.name])h=document.createElement("img"),h.src=b.icons[c.name],h.alt=c.name,d.appendChild(h);d.title=c.name;d.addEventListener("click",function(){f.querySelectorAll(".kanton-tab").forEach(function(p){p.classList.remove("active")});b.panes.forEach(function(p){(p=document.getElementById(p.id))&&p.classList.remove("active-tab")});d.classList.add("active");
var k=document.getElementById(c.id);if(k&&(k.classList.add("active-tab"),"u">typeof dijit&&"function"==typeof dijit.byId)){var l=dijit.byId(c.id);l&&!l.get("open")&&(l._wipeIn?b.setPaneOpenSafe(l):setTimeout(function(){b.setPaneOpenSafe(l)},200))}});f.appendChild(d)});e.insertBefore(f,e.firstChild);var g=document.getElementById(this.panes[0].id);g&&g.classList.add("active-tab");return a(),setTimeout(a,500),setTimeout(a,1E3),e.dataset.tabified="true",b.keepPanesOpen(),b.watchThemenkatalog(),!0},keepPanesOpen:function(){var a=
this;if(!("u"<typeof dijit||"function"!=typeof dijit.byId)){this.panes.forEach(function(e){(e=dijit.byId(e.id))&&(e._originalToggle=e.toggle,e.toggle=function(){},e._originalSetOpen=e._setOpenAttr,e._setOpenAttr=function(f){this._originalSetOpen&&this._originalSetOpen.call(this,!0)},e.set("open",!0))});var b=document.getElementById("kantons_container");b&&"u">typeof MutationObserver&&(new MutationObserver(function(e){window.__tnetResizing||a.panes.forEach(function(f){(f=document.getElementById(f.id))&&
f.classList.contains("dijitTitlePaneClosed")&&(f.classList.remove("dijitTitlePaneClosed"),f.classList.add("dijitTitlePaneOpened"),(f=f.querySelector(".dijitTitlePaneContentOuter"))&&(f.style.display="block",f.style.height="auto"))})})).observe(b,{attributes:!0,subtree:!0,attributeFilter:["class","style"]})}},watchThemenkatalog:function(){function a(){if(!window.__tnetResizing){var c=document.getElementById("kantons_tab_bar");if(c&&(c=c.querySelector(".kanton-tab.active"))){c=c.dataset.target;var h=
document.getElementById(c);if(h){h.classList.add("active-tab");var d=h.querySelector(".dijitTitlePaneContentOuter");if(d){d.removeAttribute("style");d.style.display="block";d.style.height="auto";d.style.overflow="visible";var k=d.querySelector('.dijitReset[data-dojo-attach-point="wipeNode"]');k||=d.querySelector(".dijitReset");k||=d.firstElementChild;k&&(k.removeAttribute("style"),k.style.display="block",k.style.height="auto",k.style.overflow="visible")}if(d=h.querySelector(".dijitTitlePaneTitle"))d.classList.remove("dijitTitlePaneTitleClosed",
"dijitClosed"),d.classList.add("dijitTitlePaneTitleOpen","dijitOpen"),(d=d.querySelector(".dijitTitlePaneTitleFocus"))&&d.setAttribute("aria-pressed","true");h=h.querySelector(".dijitTitlePaneContentInner");(h&&h.setAttribute("aria-hidden","false"),"u">typeof dijit&&"function"==typeof dijit.byId)&&(c=dijit.byId(c))&&(c._wipeIn=null,c._wipeOut=null,c.open=!0,c._setOpenAttr(!0),c.hideNode&&(c.hideNode.style.display="block",c.hideNode.style.height="auto"),c.wipeNode&&(c.wipeNode.style.display="block",
c.wipeNode.style.height="auto"),c.resize&&c.resize())}}}}function b(){window.__tnetResizing||(f=0,e&&clearInterval(e),e=setInterval(function(){window.__tnetResizing||(a(),f++,20<f&&(clearInterval(e),e=null))},100))}var e=null,f=0,g=document.querySelector('.leftPane, #left_pane, [data-dojo-type*="ContentPane"]');(g||=document.body,"u">typeof MutationObserver)&&(new MutationObserver(function(c){var h=!1;c.forEach(function(d){d.target&&d.target.closest&&d.target.closest(".tabs2acc-panel")||(d.target&&
d.target.classList&&(d.target.classList.contains("dijitTitlePane")||d.target.classList.contains("dijitTitlePaneContentOuter")||d.target.classList.contains("dijitReset"))&&(h=!0),"style"===d.attributeName&&d.target.dataset&&"wipeNode"===d.target.dataset.dojoAttachPoint&&(!d.target.closest||!d.target.closest(".tabs2acc-panel"))&&(h=!0))});h&&!window.__tnetResizing&&(a(),b())})).observe(g,{attributes:!0,subtree:!0,attributeFilter:["class","style"]});(["tp_overview_menu","tp_sort_menu","tp_tools_menu",
"tp_print_menu","tp_ov_menu"].forEach(function(c){(c=document.getElementById(c))&&c.addEventListener("toggle",function(){b()})}),"u">typeof dijit&&"function"==typeof dijit.byId)&&(g=dijit.byId("tp_wms_menu"))&&g.watch("open",function(){b()})},init:function(){function a(){e++;b.convert()||50<e||setTimeout(a,200)}var b=this,e=0;setTimeout(a,1E3)}},r={sections:[{id:"nw",title:"Nidwalden",icon:"resources/wappen_nidwalden.svg",maps:[]},{id:"ow",title:"Obwalden",icon:"resources/wappen_obwalden.svg",maps:[]},
{id:"ch",title:"Schweiz",icon:"resources/wappen_bund.svg",maps:[]}],bookmarksUrl:"map-bookmarks.json"},n={isOpen:!1,activeMap:null,sections:{}};window.TnetTOC={init:function(){v();console.log("[TnetTOC] Initialized")},open:function(){var a=document.querySelector("#tnetToc");a&&(a.classList.add("open"),n.isOpen=!0)},close:function(){var a=document.querySelector("#tnetToc");a&&(a.classList.remove("open"),n.isOpen=!1)},toggle:function(){n.isOpen?this.close():this.open()},setMaps:function(a,b){var e=
r.sections.find(function(g){return g.id===a});if(e){e.maps=b;var f=document.querySelector("#tnetTocItems_"+a);f&&(f.innerHTML="",b.forEach(function(g){f.appendChild(t(g))}))}},loadBookmarks:function(a){return a=a||r.bookmarksUrl,fetch(a).then(function(b){return b.json()}).then(function(b){return console.log("[TnetTOC] Bookmarks loaded:",b),b}).catch(function(b){console.error("[TnetTOC] Failed to load bookmarks:",b)})}};"loading"===document.readyState?document.addEventListener("DOMContentLoaded",u):
u()}})();
