function getAppRoot(){return window.__TNET_APP_ROOT||"/maps"}var iframeHistory=[],iframeHistoryIndex=-1;
(function(){function a(){if(!n&&!k&&window.njs&&njs.AppManager&&njs.AppManager.auth_user&&""!==njs.AppManager.auth_user){n=!0;var e="https://www.gis-daten.ch"+getAppRoot()+"/tnet/views/oauth-callback.html";e="https://www.gis-daten.ch/?option=oauthredirect&app_name=adfs&redirect_url="+encodeURIComponent(e);console.log("[tnet-header] Pre-Auth: User angemeldet \u2192 starte WP-OAuth im Hintergrund");b(e)}}function b(e){k=!1;d();c=document.createElement("iframe");c.id="_tnet_oauth_frame";c.style.cssText=
"position:fixed;width:1px;height:1px;left:-9999px;top:-9999px;opacity:0;pointer-events:none;";c.src=e;document.body.appendChild(c);console.log("[tnet-header] Versteckter OAuth-iframe erstellt");g=setTimeout(function(){k||(console.warn("[tnet-header] OAuth silent timeout (8s) \u2192 Fallback: Popup"),d(),f(e))},8E3)}function f(e){var l=window.open(e,"tnet_oauth","width=520,height=650,left="+(screen.width-520)/2+",top="+(screen.height-650)/2+",menubar=no,toolbar=no,status=no,scrollbars=yes");if(l)var p=
setInterval(function(){l&&l.closed&&(clearInterval(p),h())},500);else console.warn("[tnet-header] Popup blockiert \u2014 bitte Popup-Blocker deaktivieren")}function h(){if(!k){k=!0;d();var e=document.getElementById("mapsInfoFrame");if(e&&e.getAttribute("src")&&""!==e.getAttribute("src")){var l=e.getAttribute("data-src")||getAppRoot()+"/tnet/views/inframe-maps.html";e.src=l+(-1===l.indexOf("?")?"?t=":"&t=")+Date.now();console.log("[tnet-header] iframe refresht nach OAuth")}else console.log("[tnet-header] Pre-Auth abgeschlossen (iframe noch nicht geladen \u2014 OK)")}}
function d(){g&&(clearTimeout(g),g=null);c&&c.parentNode&&(c.parentNode.removeChild(c),c=null)}var c=null,g=null,k=!1,n=!1;window.addEventListener("message",function(e){!e.data||"object"!=typeof e.data||("tnet-oauth-popup"===e.data.type&&e.data.url&&(console.log("[tnet-header] OAuth-Request empfangen:",e.data.url),b(e.data.url)),"tnet-oauth-done"===e.data.type&&(console.log("[tnet-header] OAuth-Done empfangen"),h()))});window._tnetAppReadyFired&&a();document.addEventListener("tnet-app-ready",function(){a()},
{once:!0})})();window.setupIframeMonitoring=function(){var a=document.getElementById("mapsInfoFrame");a&&a.addEventListener("load",function(){try{var b=a.contentWindow.location.href;(-1===iframeHistoryIndex||iframeHistory[iframeHistoryIndex]!==b)&&(iframeHistory=iframeHistory.slice(0,iframeHistoryIndex+1),iframeHistory.push(b),iframeHistoryIndex=iframeHistory.length-1)}catch{}})};
window.openMapsInfoDialog=function(){var a=dijit.byId("mapsInfoDialog");if(a)if(a.open)window.closeMapsInfoDialog();else{a.show();if(a=document.getElementById("mapsInfoFrame")){var b=a.getAttribute("data-src")||"/maps/tnet/views/inframe-maps.html";a.getAttribute("src")||(a.src=b)}window.setupIframeMonitoring()}};window.closeMapsInfoDialog=function(){var a=dijit.byId("mapsInfoDialog");a&&(a.hide(),iframeHistory=[],iframeHistoryIndex=-1,(a=document.getElementById("mapsInfoFrame"))&&a.removeAttribute("src"))};
window.goBackInIframe=function(){var a=document.getElementById("mapsInfoFrame");if(a)try{a.contentWindow.history.back()}catch{0<iframeHistoryIndex&&(iframeHistoryIndex--,a.src=iframeHistory[iframeHistoryIndex])}};window.refreshIframe=function(){var a=document.getElementById("mapsInfoFrame");if(a){var b=a.getAttribute("data-src")||"/maps/tnet/views/inframe-maps.html";a.getAttribute("src")?(b=b+(-1===b.indexOf("?")?"?t=":"&t=")+Date.now(),a.src=b):a.src=b}};
function installSetMapBookmarkHook(){function a(){function h(c){if(!c)return!1;try{if("function"==typeof c.closeMapsInfoDialog)return c.closeMapsInfoDialog(),!0}catch{}try{if("u">typeof c.dijit&&"function"==typeof c.dijit.byId){var g=c.dijit.byId("mapsInfoDialog");if(g)return"function"==typeof g.hide?g.hide():"function"==typeof g.set&&g.set("open",!1),!0}}catch{}return!1}var d=!1;d=h(window)||d;(d=h(window.top)||d)&&TnetLog.log("[MapBookmark] mapsInfoDialog nach Kartenwechsel geschlossen")}if(window.__tnetSetMapBookmarkHookInstalled)return!0;
var b=window.njs&&window.njs.AppManager?window.njs.AppManager:null;if(!b||"function"!=typeof b.setMapBookmark)return!1;var f=b.setMapBookmark;return b.setMapBookmark=function(h,d){var c=null,g=null,k=null,n=null;window.__tnetLastSetMapBookmarkParams=d;window.__tnetLastSetMapBookmarkAt=Date.now();try{k=window.__tnetLastRequestedBookmark||window.top&&window.top.__tnetLastRequestedBookmark||null;try{var e=window.location.pathname.match(/\/maps\/([^\/]+)\/?$/);!k&&e&&e[1]&&TnetLog.log("[MapBookmark] Name:",
e[1])}catch{}if("string"==typeof d&&d){var l=new URLSearchParams(d),p=l.get("layers"),r=l.get("op"),q=l.get("map");q&&(n=q);p?(c=p.split("|").filter(function(m){return!!m}),TnetLog.log("[MapBookmark] Layer ON ("+c.length+"):",c),r&&(g=r.split("|").map(function(m){m=Number(m);return isFinite(m)?m:null}))):q?TnetLog.log("[MapBookmark] map=",q):TnetLog.log("[MapBookmark] params=",d)}n?TnetLog.log("[MapBookmark] Name:",n):k&&TnetLog.log("[MapBookmark] Name:",k)}catch(m){TnetLog.warn("[MapBookmark] Parse-Fehler:",
m)}"function"!=typeof b.infoFloatWinRemoveallItems&&(b.infoFloatWinRemoveallItems=function(){});k=f.apply(b,arguments);try{a(),setTimeout(a,150)}catch(m){TnetLog.warn("[MapBookmark] Dialog-Close fehlgeschlagen:",m)}return c&&c.length&&(scheduleBookmarkLayerCatchup(c),g&&g.length&&scheduleBookmarkOpacityCatchup(c,g)),k},window.__tnetSetMapBookmarkHookInstalled=!0,TnetLog.log("[MapBookmark] setMapBookmark-Hook installiert"),!0}
function scheduleBookmarkLayerCatchup(a){function b(){if("function"!=typeof window.TnetLayerSwitch)return 0;var f=window.njs&&window.njs.AppManager;f=(f=f&&f.Maps&&f.Maps.main)&&f.mapObj;if(!f||"function"!=typeof f.getLayers)return 0;var h={};f.getLayers().forEach(function(c){var g=c.get&&c.get("name");g&&(h[g]=c)});var d=0;return a.forEach(function(c){var g=h[c];if(g&&g.getVisible&&!g.getVisible())try{window.TnetLayerSwitch(c,"on"),d++}catch{}}),0<d&&TnetLog.log("[MapBookmark] Catch-up: "+d+" Layer aktiviert"),
d}a&&a.length&&(setTimeout(b,500),setTimeout(b,1500),setTimeout(b,3E3))}
function scheduleBookmarkOpacityCatchup(a,b){function f(){if(!window.TnetLMStore||"function"!=typeof window.TnetLMStore.setLayerOpacity)return 0;var h=0;return a.forEach(function(d,c){c=b[c];if(null!=c&&isFinite(c))try{window.TnetLMStore.setLayerOpacity(d,c),h++}catch{}}),0<h&&TnetLog.log("[MapBookmark] Opacity-Catch-up: "+h+" Layer aktualisiert"),h}a&&a.length&&b&&b.length&&(setTimeout(f,500),setTimeout(f,1500),setTimeout(f,3E3))}
function installSetMapBookmarkHookWithRetry(){installSetMapBookmarkHook()||(setTimeout(installSetMapBookmarkHook,500),setTimeout(installSetMapBookmarkHook,1500),setTimeout(installSetMapBookmarkHook,3E3))}
window.updateLoginStatus=function(){var a=document.getElementById("header_login"),b=document.getElementById("header_logout"),f=document.getElementById("header_username");if(window.njs&&njs.AppManager&&njs.AppManager.auth_user&&""!==njs.AppManager.auth_user){var h=njs.AppManager.auth_user;a&&(a.style.display="none");b&&(b.style.display="flex");f&&(f.textContent=h)}else a&&(a.style.display="flex"),b&&(b.style.display="none")};window.doLogout=function(){window.location.href="logout.php"};
window.toggleHeaderMenu=function(){var a=document.getElementById("header_menu");a&&a.classList.toggle("open")};window.openHelp=function(){toggleHeaderMenu();window.njs&&njs.AppManager&&njs.AppManager.toggleCustomPaneContent&&njs.AppManager.toggleCustomPaneContent("help","custompane","./core/help/help_de.htm","","")};document.addEventListener("click",function(a){var b=document.getElementById("header_menu");b&&b.classList.contains("open")&&!b.contains(a.target)&&b.classList.remove("open")});
window._tnetAppReadyFired?(updateLoginStatus(),installSetMapBookmarkHookWithRetry()):document.addEventListener("tnet-app-ready",function(){updateLoginStatus();installSetMapBookmarkHookWithRetry()},{once:!0});var headerHeight=69,minTopViewport=headerHeight+11;function adjustPanePosition(a){if(a&&!a.classList.contains("docked-right")){var b=a.getBoundingClientRect();if(b.top<minTopViewport){var f=parseInt(a.style.top)||0;a.style.setProperty("top",f+(minTopViewport-b.top)+"px","important")}}}
var floatingPaneContainer=document.getElementById("NeapoljsContainer")||document.body,bodyObserver=new MutationObserver(function(a){for(var b=0;b<a.length;b++){var f=a[b];if("childList"===f.type)for(var h=0;h<f.addedNodes.length;h++){var d=f.addedNodes[h];1===d.nodeType&&d.classList&&d.classList.contains("dojoxFloatingPane")&&(adjustPanePosition(d),(new MutationObserver(function(c){return function(){adjustPanePosition(c)}}(d))).observe(d,{attributes:!0,attributeFilter:["style"]}))}}});
bodyObserver.observe(floatingPaneContainer,{childList:!0,subtree:!0});document.querySelectorAll(".dojoxFloatingPane").forEach(function(a){adjustPanePosition(a);(new MutationObserver(function(){adjustPanePosition(a)})).observe(a,{attributes:!0,attributeFilter:["style"]})});var preloaded=!1;
function preloadMapsInfoIframe(){if(!preloaded){var a=document.getElementById("mapsInfoFrame");if(a){var b=a.getAttribute("data-src")||"/maps/tnet/views/inframe-maps.html";a.getAttribute("src")||(a.src=b);preloaded=!0}}}var opts={once:!0,passive:!0};document.addEventListener("pointerdown",preloadMapsInfoIframe,opts);document.addEventListener("keydown",preloadMapsInfoIframe,opts);document.addEventListener("touchstart",preloadMapsInfoIframe,opts);
document.addEventListener("mouseover",preloadMapsInfoIframe,opts);
