var __tnetInitialUrlLayers=null,__tnetInitialUrlOp=null,__tnetInitialUrlQuery="",__tnetBookmarkAutoStartStarted=!1,__tnetInitialUrlLayerCount=0,__tnetInitialUrlGuardUntil=Date.now()+18E3;
try{__tnetInitialUrlQuery=window.location.search||"";var __tnetInitialUrlParams=new URLSearchParams(window.location.search);__tnetInitialUrlLayers=__tnetInitialUrlParams.get("layers");__tnetInitialUrlOp=__tnetInitialUrlParams.get("op");__tnetInitialUrlLayerCount=__tnetInitialUrlLayers?__tnetInitialUrlLayers.split("|").filter(function(b){return!!b}).length:0}catch{}
__tnetInitialUrlOp&&!window.__tnetInitialOpHistoryGuardInstalled&&function(){function b(e){if(null==e)return e;try{var f=new URL(String(e),window.location.href),a=f.searchParams,g=a.get("layers")||"";g&&g.split("|").filter(function(k){return!!k});var l=__tnetInitialUrlOp.split("|").filter(function(k){return""!==k}).length;return window.__tnetInitialOpHistoryGuardEnabled&&Date.now()<__tnetInitialUrlGuardUntil&&(__tnetInitialUrlLayers&&__tnetInitialUrlLayerCount&&a.set("layers",__tnetInitialUrlLayers),
__tnetInitialUrlOp&&l===__tnetInitialUrlLayerCount&&a.set("op",__tnetInitialUrlOp)),f.pathname+(a.toString()?"?"+a.toString():"")+f.hash}catch{return e}}var d=window.history;if(d&&"function"==typeof d.replaceState){var h=d.replaceState,c=d.pushState;window.__tnetInitialOpHistoryGuardInstalled=!0;window.__tnetInitialOpHistoryGuardEnabled=!0;d.replaceState=function(e,f,a){a=b(a);if(a!==window.location.pathname+window.location.search+window.location.hash)return h.call(this,e,f,a)};"function"==typeof c&&
(d.pushState=function(e,f,a){a=b(a);if(a!==window.location.pathname+window.location.search+window.location.hash)return c.call(this,e,f,a)})}}();
__tnetInitialUrlOp&&!window.__tnetInitialOpStabilizerInstalled&&function(){function b(){try{var c=new URL(window.location.href),e=c.searchParams.get("layers")||"";e&&e.split("|").filter(function(a){return!!a});var f=c.searchParams.get("op")||"";if(Date.now()>=h||Date.now()>=__tnetInitialUrlGuardUntil||!window.__tnetInitialOpHistoryGuardEnabled)return;if(__tnetInitialUrlLayers&&c.searchParams.get("layers")!==__tnetInitialUrlLayers&&c.searchParams.set("layers",__tnetInitialUrlLayers),__tnetInitialUrlOp&&
f!==__tnetInitialUrlOp){c.searchParams.set("op",__tnetInitialUrlOp);d.replaceState(null,"",c.pathname+"?"+c.searchParams.toString()+c.hash);return}__tnetInitialUrlLayers&&c.searchParams.get("layers")!==__tnetInitialUrlLayers&&d.replaceState(null,"",c.pathname+"?"+c.searchParams.toString()+c.hash)}catch{return}"function"==typeof window.requestAnimationFrame?window.requestAnimationFrame(b):setTimeout(b,16)}var d=window.history;if(d&&"function"==typeof d.replaceState){window.__tnetInitialOpStabilizerInstalled=
!0;var h=Date.now()+2E4;b()}}();
function initPanelShadow(){function b(){var a=document.getElementById("spring");if(a){var g=a.querySelectorAll(":scope > .dijitTitlePane");g=0<g.length?g[g.length-1].getBoundingClientRect().bottom+10:h.getBoundingClientRect().bottom}else g=h.getBoundingClientRect().bottom;a=69+(a?a.scrollHeight:400)+10;g>a&&(g=a);a=h.offsetWidth||340;c.style.top="69px";c.style.height=g-69+"px";c.style.width=a+"px";d.classList.contains("close")?(c.style.width="170px",c.style.left="85px",c.style.borderRadius="0 0 4px 4px"):
(c.style.left="0px",c.style.borderRadius="0 0 4px 4px")}var d=document.getElementById("freepane"),h=document.querySelector(".close_switch");if(d&&h){var c=document.createElement("div");c.id="panelShadow";d.parentNode.insertBefore(c,d.nextSibling);b();var e=document.getElementById("spring");if("u">typeof ResizeObserver){var f=new ResizeObserver(b);f.observe(d);f.observe(h);e&&f.observe(e)}(new MutationObserver(b)).observe(d,{attributes:!0,attributeFilter:["class"]});e&&(new MutationObserver(b)).observe(e,
{childList:!0,subtree:!0,attributes:!0,attributeFilter:["class","style"]});document.addEventListener("tnet-app-ready",function(){setTimeout(b,100);setTimeout(b,500)});window.addEventListener("resize",b)}else setTimeout(initPanelShadow,200)}"loading"===document.readyState?document.addEventListener("DOMContentLoaded",initPanelShadow):initPanelShadow();function scrollSpringToTop(){var b=document.getElementById("spring");b&&b.scrollTo({top:0,behavior:"smooth"})}
function initScrollToTop(){var b=document.getElementById("spring"),d=document.getElementById("scrollToTopBtn");b&&d?b.addEventListener("scroll",function(){100<b.scrollTop?d.classList.add("visible"):d.classList.remove("visible")}):setTimeout(initScrollToTop,500)}"loading"===document.readyState?document.addEventListener("DOMContentLoaded",initScrollToTop):initScrollToTop();
function announcePendingBookmarkLoad(b,d){try{window.__tnetPendingBookmarkLoad={id:b,name:b,viewId:d||null,source:"url-autostart",startedAt:Date.now()},document.dispatchEvent(new CustomEvent("tnet-bookmark-loading",{detail:{reason:"url-autostart",pending:window.__tnetPendingBookmarkLoad,bookmark:window.__tnetActiveBookmark||null}}))}catch{}}
function startBookmarkFromUrl(){var b=window.location.pathname.match(/\/maps(?:-dev)?\/([a-zA-Z0-9_-]+)$/);if(b&&b[1]){let l=function(){if("function"==typeof window.TnetSetBookmark&&window.njs&&window.njs.AppManager&&"function"==typeof window.njs.AppManager.setMapBookmark){var k=c&&/[?&](lang|basemap|blop|x|y|zl|hl|theme|subtheme|layers|op|view)=/.test(c)?{visibleLayerIds:e?e.split("|").filter(function(m){return!!m}):null,originalVisibleLayerIds:e?e.split("|").filter(function(m){return!!m}):null,
opacityValues:f?f.split("|"):null,originalOp:f||"",urlQuery:c,urlOverride:!0}:null;window.TnetSetBookmark(d,h,k)}else setTimeout(l,200)};if(!__tnetBookmarkAutoStartStarted){__tnetBookmarkAutoStartStarted=!0;var d=b[1],h=null,c=__tnetInitialUrlQuery||window.__tnetOriginalUrlQuery||"",e=__tnetInitialUrlLayers||window.__tnetOriginalUrlLayers||null,f=__tnetInitialUrlOp||window.__tnetOriginalUrlOp||null;try{var a=new URLSearchParams(window.location.search),g=a.get("view");g&&/^[a-zA-Z0-9_-]+$/.test(g)&&
(h=g);e||=a.get("layers");f||=a.get("op")}catch{}announcePendingBookmarkLoad(d,h);l()}}}window._tnetAppReadyFired?startBookmarkFromUrl():document.addEventListener("tnet-app-ready",function(){startBookmarkFromUrl()},{once:!0});setTimeout(startBookmarkFromUrl,1500);setTimeout(startBookmarkFromUrl,3500);setTimeout(startBookmarkFromUrl,7E3);
