(function(){function t(){return window.__TNET_APP_ROOT||"/maps"}function x(){return TnetIcons.get("legend-colors",null,{width:"14",height:"14",style:"vertical-align:-2px"})}function l(a){return a||0===a?(y||=document.createElement("div"),y.textContent=String(a),y.innerHTML):""}var h=null,z=null,p=null,u={},q=[],v="",r=null,n={},A={nidwalden:{label:"Nidwalden",wappen:t()+"/tnet/resources/wappen_nidwalden.svg"},obwalden:{label:"Obwalden",wappen:t()+"/tnet/resources/wappen_obwalden.svg"},bund:{label:"Bundesdaten",
wappen:t()+"/tnet/resources/wappen_bund.svg"},weitere:{label:"Weitere Geodaten",wappen:t()+"/tnet/resources/icon_weitere.svg"}},B={nidwalden:"Nidwalden",obwalden:"Obwalden",bund:"Bundesdaten",weitere:"Weitere Geodaten"},y=null;window.TnetLMTree={init:function(a){if(h=document.getElementById(a),h){var c=window.TnetLMStore;if(c){q.push(c.on("catalog-loaded",this.render.bind(this)));q.push(c.on("layer-visibility",this._onLayerVisibility.bind(this)));q.push(c.on("layer-loading",this._onLayerLoading.bind(this)));
q.push(c.on("active-layers-changed",this._onActiveLayersChanged.bind(this)));q.push(c.on("group-toggled",this._onGroupToggled.bind(this)));var b=this,d=function(){b._syncToActiveBookmark()};document.addEventListener("tnet-bookmark-loaded",d);q.push(function(){document.removeEventListener("tnet-bookmark-loaded",d)});c.isLoaded()&&this.render(c.getCatalog());this._initResolutionWatch();window.__tnetActiveBookmark&&this._syncToActiveBookmark();TnetLog.log("[LM-Tree]","Init \u2713 \u2192 #"+a)}else TnetLog.error("[LM-Tree]",
"TnetLMStore nicht geladen")}else TnetLog.error("[LM-Tree]","Container #"+a+" nicht gefunden")},destroy:function(){r&&("function"==typeof cancelAnimationFrame?cancelAnimationFrame(r):clearTimeout(r),r=null);Object.keys(n).forEach(function(a){clearTimeout(n[a])});n={};q.forEach(function(a){a()});q=[];h&&(h.innerHTML="")},render:function(a){if(h&&a&&a.length){p||=a[0].id;u={};v="";var c='<div class="lm-tab-bar">';for(var b=0;b<a.length;b++){var d=a[b],e=A[d.id]||{label:d.name.substring(0,2).toUpperCase()},
f=B[d.id]||d.alias||d.name;c+='<div class="lm-tab'+(d.id===p?" lm-tab-active":"")+'" data-cat-id="'+l(d.id)+'" title="'+l(f)+'">';e.wappen?c+='<img class="lm-tab-icon" src="'+l(e.wappen)+'" alt="'+l(f)+'" title="'+l(f)+'">':c+='<span class="lm-tab-label" title="'+l(f)+'">'+l(e.label)+"</span>";c+="</div>"}c+='</div><div class="lm-search-wrap"><input type="text" class="lm-search" placeholder="Thema suchen\u2026"><span class="lm-search-clear" style="display:none">&times;</span></div>';for(b=0;b<a.length;b++)d=
a[b],e=d.id===p,c+='<div class="lm-cat-content" data-cat-content="'+l(d.id)+'"',c+=e?">":' style="display:none">',e&&(c+=this._renderCategory(d),u[d.id]=!0),c+="</div>";h.innerHTML=c+'<div class="lm-no-results" style="display:none">Keine Themen gefunden</div>';this._bindEvents();this._resyncLayerCheckboxes();document.dispatchEvent(new CustomEvent("lm-catalog-rendered",{bubbles:!1}))}},_renderCategory:function(a){a=a.subcategories||[];for(var c="",b=0;b<a.length;b++)c+=this._renderSubcategory(a[b]);
return c},_renderSubcategory:function(a){var c=this._clampDepth(1),b=a.groups||[],d=this._countLeaves(b);var e='<div class="lm-subcat'+(!1!==a.expanded?" lm-expanded":" lm-collapsed")+'" data-group-id="'+l(a.id)+'">';e+='<div class="lm-subcat-header lm-depth-'+c+'" data-action="toggle-group" data-lm-depth="'+c+'"><span class="lm-arrow">\u25b6</span>';e+='<span class="lm-subcat-name">'+l(a.name)+"</span>";e+='<span class="lm-count">'+d+"</span>";e+="</div>";e+='<div class="lm-subcat-body">';for(a=
0;a<b.length;a++)e+=this._renderGroup(b[a],2);return e+="</div>",e+="</div>",e},_renderGroup:function(a,c){c=this._clampDepth(c);var b=a.layers||[];if(1===b.length&&"group"!==b[0].type)return this._renderLeafLayer(b[0],c);var d=this._countLeaves(b),e=!0===a.selectAll,f=a.legend&&""!==a.legend;var g='<div class="lm-group'+(!0===a.open||!0===a.expanded?" lm-expanded":" lm-collapsed")+" lm-depth-"+c+'" data-group-id="'+l(a.id)+'" data-lm-depth="'+c+'">';g+='<div class="lm-group-header lm-depth-'+c+'" data-action="toggle-group" data-lm-depth="'+
c+'"><span class="lm-arrow">\u25b6</span>';e&&(g+='<input type="checkbox" class="lm-group-cb" data-action="select-all" data-group-id="'+l(a.id)+'" title="Alle Layer ein-/ausschalten">');g+='<span class="lm-group-name">'+l(a.name)+"</span>";f&&(g+='<button class="lm-legend-btn" data-action="open-legend" data-legend-key="'+l(a.legend)+'"',a.legendLink&&(g+=' data-legend-link="'+l(a.legendLink)+'"'),a.legendTitle&&(g+=' data-legend-title="'+l(a.legendTitle)+'"'),g+=' title="Legende anzeigen">'+x()+"</button>");
g+='<span class="lm-count">'+d+"</span>";g+="</div>";g+='<div class="lm-group-body">';for(a=0;a<b.length;a++)g+=this._renderLayerItem(b[a],c+1);return g+="</div>",g+="</div>",g},_renderLayerItem:function(a,c){c=this._clampDepth(c);if("group"===a.type&&a.layers&&a.layers.length){var b=this._countLeaves(a.layers),d=!0===a.selectAll,e=a.legend&&""!==a.legend;var f='<div class="lm-nested-group'+(!0===a.open||!0===a.expanded?" lm-expanded":" lm-collapsed")+" lm-depth-"+c+'" data-group-id="'+l(a.id)+'" data-lm-depth="'+
c+'">';f+='<div class="lm-nested-header lm-depth-'+c+'" data-action="toggle-group" data-lm-depth="'+c+'"><span class="lm-arrow">\u25b6</span>';d&&(f+='<input type="checkbox" class="lm-group-cb" data-action="select-all" data-group-id="'+l(a.id)+'" title="Alle Layer ein-/ausschalten">');f+='<span class="lm-nested-name">'+l(a.name)+"</span>";e&&(f+='<button class="lm-legend-btn" data-action="open-legend" data-legend-key="'+l(a.legend)+'"',a.legendLink&&(f+=' data-legend-link="'+l(a.legendLink)+'"'),
a.legendTitle&&(f+=' data-legend-title="'+l(a.legendTitle)+'"'),f+=' title="Legende anzeigen">'+x()+"</button>");f+='<span class="lm-count">'+b+"</span>";f+="</div>";f+='<div class="lm-nested-body">';for(b=0;b<a.layers.length;b++)f+=this._renderLayerItem(a.layers[b],c+1);return f+="</div>",f+="</div>",f}return this._renderLeafLayer(a,c)},_renderLeafLayer:function(a,c){var b=this._clampDepth(c),d=a.visible?" checked":"",e=a.visible?" lm-active":"",f=a.legend&&""!==a.legend,g=a._missing?" lm-layer--missing":
"",k=a._missing?' data-missing="1"':"",m="";a.loading&&(m+=" lm-layer-loading");a.loadingSlow&&(m+=" lm-layer-slow");a.loadingError&&(m+=" lm-layer-error");c="";if(c+='<div class="lm-layer lm-depth-'+b+e+g+m+'" data-layer-id="'+l(a.id)+'" data-lm-depth="'+b+'"'+k+' data-name="'+l((a.name||"").toLowerCase())+'">',c+='<label class="lm-layer-label">',c+='<span class="lm-cb-wrap">',c+='<input type="checkbox" class="lm-cb"'+d+' data-action="toggle-layer">',c+="</span>",c+='<span class="lm-layer-name">'+
l(a.name)+"</span>",a._missing&&(c+='<span class="lm-layer-missing-badge" title="Keine Layer-Definition in der Datenbank">\u26a0 fehlt</span>'),c+="</label>",f)b=a.legendLayers||"",c+='<button class="lm-legend-btn" data-action="open-legend" data-legend-key="'+l(a.legend)+'"',b&&(c+=' data-legend-layers="'+l(b)+'"'),a.legendLink&&(c+=' data-legend-link="'+l(a.legendLink)+'"'),a.legendTitle&&(c+=' data-legend-title="'+l(a.legendTitle)+'"'),c+=' title="Legende anzeigen">'+x()+"</button>";return c+="</div>",
c},_bindEvents:function(){if(!h.__tnetLmTreeBound){h.__tnetLmTreeBound=!0;var a=this;h.addEventListener("click",function(b){var d=b.target.closest(".lm-tab");if(d)(d=d.dataset.catId)&&d!==p&&a._switchTab(d);else if(d=b.target.closest('[data-action="open-legend"]'))b.stopPropagation(),a._openLegend(d.dataset.legendKey,d.dataset.legendLayers||"",d.dataset.legendLink||"",d.dataset.legendTitle||"");else if(b.target.matches('[data-action="select-all"]'))b.stopPropagation();else{var e=b.target.closest('[data-action="toggle-group"]');
if(e){var f=e.closest(".lm-subcat, .lm-group, .lm-nested-group");if(f)if(b.preventDefault(),d=f.classList.contains("lm-collapsed"),b.ctrlKey||b.metaKey){if(b=e.getAttribute("data-lm-depth"),(f=f.parentElement)&&b){f=f.querySelectorAll(':scope > .lm-subcat,:scope > .lm-group[data-lm-depth="'+b+'"],:scope > .lm-nested-group[data-lm-depth="'+b+'"]');for(e=0;e<f.length;e++)d?(f[e].classList.add("lm-expanded"),f[e].classList.remove("lm-collapsed")):(f[e].classList.remove("lm-expanded"),f[e].classList.add("lm-collapsed"));
TnetLog.debug("[LM-Tree]","Ctrl+Klick: Tiefe",b,"\u2192",f.length,"Knoten",d?"ge\u00f6ffnet":"geschlossen")}}else d?(f.classList.add("lm-expanded"),f.classList.remove("lm-collapsed")):(f.classList.remove("lm-expanded"),f.classList.add("lm-collapsed")),TnetLog.debug("[LM-Tree]","Toggle:",f.dataset.groupId,d?"\u2192 offen":"\u2192 geschlossen","classes:",f.className.substring(0,60));else TnetLog.warn("[LM-Tree]","Toggle: kein Gruppen-Element gefunden f\u00fcr",e)}else b.target.closest(".lm-search-clear")&&
((d=h.querySelector(".lm-search"))&&(d.value="",d.focus()),a._applyFilter(""))}});h.addEventListener("change",function(b){if(b.target.matches('[data-action="toggle-layer"]'))(b=b.target.closest(".lm-layer"))&&window.TnetLMStore.toggleLayer(b.dataset.layerId);else if(b.target.matches('[data-action="select-all"]')){var d=b.target.dataset.groupId,e=b.target.checked;d&&window.TnetLMStore&&(window.TnetLMStore.setGroupAllVisible(d,e),setTimeout(function(){a._syncGroupCheckboxes(d,e)},1200))}});var c=h.querySelector(".lm-search");
c&&c.addEventListener("input",function(){clearTimeout(z);var b=c.value;z=setTimeout(function(){a._applyFilter(b)},200)})}},_switchTab:function(a){p=a;for(var c=h.querySelectorAll(".lm-tab"),b=0;b<c.length;b++)c[b].classList.toggle("lm-tab-active",c[b].dataset.catId===a);c=h.querySelectorAll(".lm-cat-content");for(b=0;b<c.length;b++){var d=c[b].dataset.catContent===a;if(c[b].style.display=d?"":"none",d&&!u[a]){d=(d=window.TnetLMStore)?d.getCatalog():[];for(var e=0;e<d.length;e++)if(d[e].id===a){c[b].innerHTML=
this._renderCategory(d[e]);u[a]=!0;break}}}this._resyncLayerCheckboxes();v&&this._applyFilter(v)},_applyFilter:function(a){v=a;var c=(a||"").trim().toLowerCase();a=h.querySelector(".lm-search-clear");var b=h.querySelector(".lm-search-wrap");a&&(a.style.display=c?"":"none");b&&b.classList.toggle("lm-search-active",!!c);if(a=h.querySelector('.lm-cat-content[data-cat-content="'+p+'"]')){var d=a.querySelectorAll(".lm-layer");a=a.querySelectorAll(".lm-subcat, .lm-group, .lm-nested-group");if(!c||2>c.length){for(b=
0;b<d.length;b++)d[b].style.display="",d[b].classList.remove("lm-filter-match");for(b=0;b<a.length;b++)a[b].style.display="",a[b].classList.contains("lm-filter-open")&&(a[b].classList.remove("lm-filter-open"),"collapsed"===a[b].dataset.preFilterState&&(a[b].classList.remove("lm-expanded"),a[b].classList.add("lm-collapsed")),delete a[b].dataset.preFilterState);(a=h.querySelector(".lm-no-results"))&&(a.style.display="none")}else{for(var e=b=0;e<d.length;e++){var f=d[e],g=-1!==(f.dataset.name||"").indexOf(c);
f.style.display=g?"":"none";f.classList.toggle("lm-filter-match",g);g&&b++}for(c=a.length-1;0<=c;c--)if(d=a[c],f=d.querySelector(".lm-subcat-body, .lm-group-body, .lm-nested-body")){e=!1;g=f.querySelectorAll(":scope > .lm-layer");for(var k=0;k<g.length;k++)if("none"!==g[k].style.display){e=!0;break}if(!e)for(f=f.querySelectorAll(":scope > .lm-group, :scope > .lm-nested-group"),g=0;g<f.length;g++)if("none"!==f[g].style.display){e=!0;break}d.style.display=e?"":"none";e&&!d.classList.contains("lm-filter-open")&&
(d.dataset.preFilterState||(d.dataset.preFilterState=d.classList.contains("lm-collapsed")?"collapsed":"expanded"),d.classList.add("lm-expanded","lm-filter-open"),d.classList.remove("lm-collapsed"))}else d.style.display="none";(a=h.querySelector(".lm-no-results"))&&(a.style.display=0===b?"":"none")}}},_onLayerVisibility:function(a){if(h){for(var c=this,b=h.querySelectorAll('[data-layer-id="'+a.id+'"]'),d=0;d<b.length;d++){var e=b[d].querySelector(".lm-cb");e&&(e.checked=a.visible);b[d].classList.toggle("lm-active",
a.visible);a.visible?(b[d].classList.add("lm-layer-loading","lm-layer-loading-hint"),b[d].classList.remove("lm-layer-error")):b[d].classList.remove("lm-layer-loading","lm-layer-loading-hint","lm-layer-loading-real","lm-layer-slow","lm-layer-error")}n[a.id]&&(clearTimeout(n[a.id]),delete n[a.id]);a.visible&&(n[a.id]=setTimeout(function(){delete n[a.id];for(var f=h?h.querySelectorAll('[data-layer-id="'+a.id+'"]'):[],g=0;g<f.length;g++)f[g].classList.remove("lm-layer-loading-hint"),f[g].classList.contains("lm-layer-loading-real")||
f[g].classList.remove("lm-layer-loading");c._updateSelectAllCheckboxes()},1400));this._updateSelectAllCheckboxes()}},_onLayerLoading:function(a){if(h&&a&&a.id){var c=a.state||{},b=!(!c.loading&&!c.loadingSlow),d=!!c.loadingError,e=h.querySelectorAll('[data-layer-id="'+a.id+'"]');n[a.id]&&(clearTimeout(n[a.id]),delete n[a.id]);for(a=0;a<e.length;a++){var f=e[a],g=f.querySelector(".lm-layer-status");g&&g.remove();f.classList.toggle("lm-layer-slow",!!c.loadingSlow);f.classList.toggle("lm-layer-error",
!b&&d);b?(f.classList.add("lm-layer-loading","lm-layer-loading-real"),f.classList.remove("lm-layer-loading-hint")):(f.classList.remove("lm-layer-loading-real","lm-layer-loading-hint"),f.classList.remove("lm-layer-loading"))}}},_onActiveLayersChanged:function(){if(!r){var a=this,c=function(){r=null;a._resyncLayerCheckboxes()};r="function"==typeof requestAnimationFrame?requestAnimationFrame(c):setTimeout(c,16)}},_onGroupToggled:function(a){if(h)for(var c=h.querySelectorAll('[data-group-id="'+a.id+'"]'),
b=0;b<c.length;b++)c[b].classList.toggle("lm-expanded",a.expanded),c[b].classList.toggle("lm-collapsed",!a.expanded)},_updateSelectAllCheckboxes:function(){if(h){var a=window.TnetLMStore;if(a&&"function"==typeof a.getGroupVisibilityState)for(var c=h.querySelectorAll('.lm-group-cb[data-action="select-all"]'),b=0;b<c.length;b++){var d=c[b].dataset.groupId;if(d){d=a.getGroupVisibilityState(d);c[b].checked="all"===d;c[b].indeterminate="partial"===d;var e=c[b].closest("[data-group-id]");e&&e.classList.toggle("lm-partial",
"partial"===d)}}}},_resyncLayerCheckboxes:function(){if(h){var a=window.TnetLMStore;if(a&&(a="function"==typeof a.isLayerRequestedVisible?a.isLayerRequestedVisible.bind(a):"function"==typeof a.isLayerEffectivelyVisible?a.isLayerEffectivelyVisible.bind(a):null)){for(var c=h.querySelectorAll(".lm-layer[data-layer-id]"),b=0;b<c.length;b++){var d=c[b].dataset.layerId;if(d){d=a(d);var e=c[b].querySelector(".lm-cb");e&&(e.checked=d);c[b].classList.toggle("lm-active",d)}}this._updateSelectAllCheckboxes()}}},
_syncToActiveBookmark:function(){var a=window.__tnetActiveBookmark;if(a&&h&&!a.themes){a=Array.isArray(a.layers)?a.layers:[];for(var c=null,b=0;b<a.length;b++)if(a[b]&&a[b].id&&!1!==a[b].visible){c=a[b].id;break}!c&&a.length&&a[0]&&a[0].id&&(c=a[0].id);c&&this.navigateToLayer(c)}},_initResolutionWatch:function(){function a(){var b="u">typeof njs&&njs.AppManager&&njs.AppManager.Maps&&njs.AppManager.Maps.main;if(b=b&&b.mapObj){var d=b.getView();if(d){var e=null;d.on("change:resolution",function(){clearTimeout(e);
e=setTimeout(function(){c._updateOutOfRange(d.getResolution())},200)});c._updateOutOfRange(d.getResolution());TnetLog.log("[LM-Tree]","Resolution-Watch aktiv")}}else setTimeout(a,2E3)}var c=this;a()},_updateOutOfRange:function(a){if(h){var c=window.TnetLMStore;if(c)for(var b=h.querySelectorAll(".lm-layer[data-layer-id]"),d=0;d<b.length;d++){var e=c.findLayer(b[d].dataset.layerId);if(e){var f=e.maxResolution,g=e.minResolution;if(e._olLayerRef){var k=e._olLayerRef.getMaxResolution();e=e._olLayerRef.getMinResolution();
k&&k!==1/0&&(f=k);e&&0<e&&(g=e)}k=!1;f&&a>f&&(k=!0);g&&a<g&&(k=!0);b[d].classList.toggle("lm-out-of-range",k)}}}},_syncGroupCheckboxes:function(a,c){if(h){var b=h.querySelector('[data-group-id="'+a+'"]');if(b){b=b.querySelectorAll(".lm-layer");var d=window.TnetLMStore;d=d&&"function"==typeof d.isLayerRequestedVisible?d.isLayerRequestedVisible.bind(d):d&&"function"==typeof d.isLayerEffectivelyVisible?d.isLayerEffectivelyVisible.bind(d):null;for(var e=0,f=0;f<b.length;f++){var g=b[f].querySelector(".lm-cb");
if(g&&g.checked!==c){var k=b[f].dataset.layerId;d&&d(k)===c&&(g.checked=c,b[f].classList.toggle("lm-active",c),e++)}}0<e&&TnetLog.log("[LMTree]","_syncGroupCheckboxes:",e,"Checkboxen korrigiert f\u00fcr",a);this._updateSelectAllCheckboxes()}}},_openLegend:function(a,c,b,d){if(a){var e;b?e=b:(e=t()+"/tnet/api/v1/legend-proxy.php?service="+encodeURIComponent(a),c&&(e+="&layers="+encodeURIComponent(c)));(window.__TNET_LEGEND_CONFIG||{}).metadata&&-1!==e.indexOf("legend-proxy")&&-1===e.indexOf("metadata=")&&
(e+=(-1!==e.indexOf("?")?"&":"?")+"metadata=1");a=d||a.split("/").pop()||"Legende";(c=window.njs&&window.njs.AppManager)||(c=window.top&&window.top.njs&&window.top.njs.AppManager);c&&"function"==typeof c.showLegend?(c.showLegend(e,a,!0,void 0),TnetLog.log("[LM-Tree]","Legende ge\u00f6ffnet:",e)):window.open(e,"_blank","noopener")}},_countLeaves:function(a){for(var c=0,b=0;b<a.length;b++){var d=a[b],e=d.layers||d.groups;e&&e.length?c+=this._countLeaves(e):"group"!==d.type&&c++}return c},_clampDepth:function(a){a=
parseInt(a,10);return!isFinite(a)||1>a?1:6<a?6:a},navigateToLayer:function(a,c){function b(){var g=h.querySelector('[data-layer-id="'+a+'"]');if(!g&&5>f)f++,setTimeout(b,150);else{if(!g){for(var k=a.split("/");!g&&1<k.length;){k.pop();var m=k.join("/");g=h.querySelector('[data-layer-id="'+m+'"]')}if(!g){TnetLog.warn("[LM-Tree]","navigateToLayer: Layer nicht im DOM gefunden:",a);return}TnetLog.log("[LM-Tree]","navigateToLayer: Eltern-Element gefunden:",k.join("/"),"(statt:",a,")")}for(k=g.parentElement;k&&
k!==h;)k.dataset&&void 0!==k.dataset.groupId&&(k.classList.add("lm-expanded"),k.classList.remove("lm-collapsed")),k=k.parentElement;g.scrollIntoView({behavior:"smooth",block:"center"});g.classList.add("lm-highlight");setTimeout(function(){g.classList.remove("lm-highlight")},2500)}}if(!h||!a)return!1;var d=window.TnetLMStore;if(!d)return!1;c=c||null;if(!c){d=d.getCatalog();for(var e=0;e<d.length;e++)if(this._catalogNodeContainsLayer(d[e],a)){c=d[e].id;break}}c&&c!==p&&this._switchTab(c);var f=0;return setTimeout(b,
80),!0},_catalogNodeContainsLayer:function(a,c){if(a.id===c)return!0;a=a.subcategories||a.groups||a.layers||[];for(var b=0;b<a.length;b++)if(this._catalogNodeContainsLayer(a[b],c))return!0;return!1},navigateToSubcategory:function(a,c){function b(){var g=h;if(c){var k=h.querySelector('[data-cat-content="'+c+'"]');k&&(g=k)}k=g.querySelector('.lm-subcat[data-group-id="'+e+'"]');if(!k){g=g.querySelectorAll(".lm-subcat-name");for(var m=0;m<g.length;m++)if(g[m].textContent.trim().toLowerCase()===e){var w=
g[m].closest(".lm-subcat");if(w){k=w;break}}}return k}function d(){var g=b();!g&&5>f?(f++,setTimeout(d,150)):g?(g.classList.add("lm-expanded"),g.classList.remove("lm-collapsed"),(g.querySelector(".lm-subcat-header")||g).scrollIntoView({behavior:"smooth",block:"start"}),g.classList.add("lm-highlight"),setTimeout(function(){g.classList.remove("lm-highlight")},2500),TnetLog.log("[LM-Tree]","navigateToSubcategory:",a,"\u2192",g.dataset.groupId)):TnetLog.warn("[LM-Tree]","navigateToSubcategory: nicht gefunden:",
a,"(Kategorie:",c||"alle",")")}if(!h||!a||!window.TnetLMStore)return!1;var e=a.trim().toLowerCase();c&&c!==p&&this._switchTab(c);var f=0;return setTimeout(d,80),!0},expandThemes:function(a){if(a&&h){var c=this,b={ow:"obwalden",nw:"nidwalden",ch:"bund",we:"weitere"},d=window.__tnetActiveBookmark;d=!(!d||!Array.isArray(d.layers));var e=document.getElementById("tp_overview_menu");!d&&e&&!e.open&&(e.open=!0);a=a.split(",");for(d=0;d<a.length;d++)if(e=a[d].trim()){var f=null,g=e,k=e.indexOf(":");if(0<
k&&3>=k){var m=e.substring(0,k).toLowerCase();b[m]&&(f=b[m],g=e.substring(k+1).trim())}(function(w,C,D){setTimeout(function(){c.navigateToSubcategory(w,C)},D)})(g,f,300*d)}}}}})();
