(function(){function x(){return window.__TNET_APP_ROOT||"/maps"}function A(){try{return njs.AppManager.Maps.main.mapObj.getView()}catch{return null}}function B(){a:{try{if(/swissimage|ortho/i.test(njs.AppManager.Maps.main.currBasisMap||njs.AppManager.Maps.main.basisMap||"")){var a=!0;break a}}catch{}a=document.querySelector(".basemap-card.active");a=!(!a||!/swissimage|ortho/i.test(a.dataset.basemap||""))}a=a?"orthophoto":"other";if(C&&C[a]){var b=C[a];return{point:null!=b.point?b.point:"orthophoto"===
a?25:24,fitMax:null!=b.fitMax?b.fitMax:"orthophoto"===a?25:24,fitMin:null!=b.fitMin?b.fitMin:"orthophoto"===a?16:15,panDefault:null!=b.panDefault?b.panDefault:"orthophoto"===a?25:24}}return"orthophoto"===a?{point:25,fitMax:25,fitMin:16,panDefault:25}:{point:24,fitMax:24,fitMin:15,panDefault:24}}function p(a,b,f,d){var e=A();if(e&&null!=a&&null!=b){var g=e.getProjection().getCode();a="u">typeof ol&&ol.proj?ol.proj.transform([b,a],"EPSG:2056",g):[b,a];d?e.animate({center:a,resolution:d,duration:400}):
(d=B(),e.animate({center:a,zoom:f||d.panDefault,duration:400}))}}function V(){if(!I&&!D){D=!0;var a=x()+"/tnet/api/v1/layers.php?flat=true&details=false";fetch(a).then(function(b){return b.ok?b.json():Promise.reject(b.status)}).then(function(b){t=b.data||b||[];Array.isArray(t)&&0<t.length?(I=!0,TnetLog.log("[DesktopSearch] Layer-Index geladen:",t.length,"Layer")):TnetLog.warn("[DesktopSearch] Layer-Index leer oder ungueltiges Format");D=!1}).catch(function(b){D=!1;TnetLog.warn("[DesktopSearch] Layer-Index konnte nicht geladen werden:",
b)})}}function W(a,b){if(!t||!t.length)return[];var f=a.toLowerCase();a=[];for(var d=0;d<t.length;d++){var e=t[d],g=e.name||"",c=g.toLowerCase(),h=(e.id||"").replace(/[_\/]/g," ").toLowerCase(),k=0;if(c===f?k=100:0===c.indexOf(f)?k=80:-1!==c.indexOf(f)?k=60:-1!==h.indexOf(f)&&(k=20),0!==k){var l=(e.path||"").split(" > ");h=(e.category||"").toLowerCase();(0<l.length&&(l[0]=X[h]||l[0]),2<l.length)&&l[l.length-1].toLowerCase().replace(/[\s_-]/g,"")===c.replace(/[\s_-]/g,"")&&l.pop();c=l.join(" \u203a ");
a.push({id:e.id,label:g,subtitle:c,type:"layer",layer:e.id,category:e.category||"",x:null,y:null,_score:k,_catOrder:Y[h]||99})}}a.sort(function(m,q){return m._score!==q._score?q._score-m._score:m._catOrder-q._catOrder});a=a.slice(0,b||10);for(b=0;b<a.length;b++)delete a[b]._score,delete a[b]._catOrder;return a}function E(a,b){if(!b||!b.length)return a||[];if(!a||!a.length)return[{label:"Themen",type:"layer",items:b}];for(var f=[],d=0;d<a.length;d++)"layer"!==a[d].type&&f.push(a[d]);return f.push({label:"Themen",
type:"layer",items:b}),f}function J(){if(u)return u;try{var a=njs.AppManager.Maps.main.mapObj;u=new ol.layer.Vector({source:new ol.source.Vector,name:"tnet_feature_highlight",zIndex:9999,style:new ol.style.Style({stroke:new ol.style.Stroke({color:"#e74c3c",width:4}),fill:new ol.style.Fill({color:"rgba(231,76,60,0.15)"}),image:new ol.style.Circle({radius:8,fill:new ol.style.Fill({color:"#e74c3c"}),stroke:new ol.style.Stroke({color:"#fff",width:2})})})});a.addLayer(u)}catch(b){TnetLog.warn("[DesktopSearch] Feature-Highlight-Layer konnte nicht erstellt werden:",
b)}return u}function F(){u&&u.getSource().clear()}function O(a,b){var f=J();if(f&&null!=a&&null!=b){var d=A();d&&(d=d.getProjection().getCode(),a=ol.proj.transform([b,a],"EPSG:2056",d),a=new ol.Feature({geometry:new ol.geom.Point(a)}),f.getSource().addFeature(a))}}function Z(a){function b(){a.x&&a.y&&(O(a.x,a.y),"Adresse"===a.subtitle?p(a.x,a.y,null,.28):p(a.x,a.y),TnetLog.log("[DesktopSearch] Fallback: Pan + Marker f\u00fcr",a.label))}var f=J();if(f){F();var d="https://api3.geo.admin.ch/rest/services/api/MapServer/"+
encodeURIComponent(a.layerId)+"/"+encodeURIComponent(a.featureId)+"?sr=2056&geometryFormat=geojson",e=new XMLHttpRequest;e.open("GET",d,!0);e.timeout=8E3;e.onload=function(){if(200!==e.status)TnetLog.warn("[DesktopSearch] MapServer HTTP",e.status,"f\u00fcr",a.layerId),b();else try{var g=JSON.parse(e.responseText),c=g.feature||g,h=A();if(h){var k=h.getProjection().getCode(),l=(new ol.format.GeoJSON).readFeatures(c,{dataProjection:"EPSG:2056",featureProjection:k});if(l.length){f.getSource().addFeatures(l);
var m=l[0].getGeometry().getExtent().slice();for(g=1;g<l.length;g++)ol.extent.extend(m,l[g].getGeometry().getExtent());TnetLog.log("[DesktopSearch] Feature extent:",m);var q=m[3]-m[1];if(1<m[2]-m[0]||1<q){var y=B();h.fit(m,{padding:[50,50,50,50],minZoom:y.fitMin,maxZoom:y.fitMax,duration:500,constrainResolution:!1})}else{var G=(m[0]+m[2])/2,P=(m[1]+m[3])/2;if("Adresse"===a.subtitle)h.animate({center:[G,P],resolution:.28,duration:500});else{var aa=B();h.animate({center:[G,P],zoom:aa.point,duration:500})}}}else b()}}catch(ba){TnetLog.warn("[DesktopSearch] Feature-Geometrie konnte nicht geladen werden:",
ba),b()}};e.onerror=e.ontimeout=function(){TnetLog.warn("[DesktopSearch] Feature-Geometrie Timeout/Fehler");b()};e.send()}}function ca(a,b){var f=J();if(f){F();var d=new XMLHttpRequest;d.open("GET","https://api3.geo.admin.ch/rest/services/ech/MapServer/identify?geometryType=esriGeometryPoint&geometry="+Math.round(b)+","+Math.round(a)+"&tolerance=0&layers=all:ch.kantone.cadastralwebmap-farbe&returnGeometry=true&sr=2056&geometryFormat=geojson",!0);d.timeout=8E3;d.onload=function(){if(200===d.status)try{var e=
JSON.parse(d.responseText);if(e.results&&e.results.length){var g=A();if(g){var c=g.getProjection().getCode(),h=e.results[0],k=h.geometry;if(k){var l={type:"Feature",geometry:k,properties:h.properties||{}},m=(new ol.format.GeoJSON).readFeatures(l,{dataProjection:"EPSG:2056",featureProjection:c});if(m.length){f.getSource().addFeatures(m);var q=m[0].getGeometry().getExtent().slice();for(e=1;e<m.length;e++)ol.extent.extend(q,m[e].getGeometry().getExtent());TnetLog.log("[DesktopSearch] Parcel extent:",
q);var y=B();g.fit(q,{padding:[50,50,50,50],minZoom:y.fitMin,maxZoom:y.fitMax,duration:500,constrainResolution:!1})}else p(a,b)}else p(a,b)}}else p(a,b)}catch(G){TnetLog.warn("[DesktopSearch] Parcel-Geometrie Fehler:",G),p(a,b)}};d.onerror=d.ontimeout=function(){TnetLog.warn("[DesktopSearch] Parcel-Identify Timeout");p(a,b)};d.send()}}function r(a){return H[a]||K.location}function da(a){if("layer"===a.type)return r("layer");var b=(a.subtitle||"").toLowerCase();return"strasse"===b?r("street"):"adresse"===
b?r("address"):"gemeinde"===b||"plz"===b||"kanton"===b||"ortschaft"===b||"bezirk"===b?r("location"):"feature"===a.type&&"ch.swisstopo.swissnames3d"===a.layerId?/gipfel|berg|pass|gletscher|huegel/i.test(b)?r("terrain"):r("location"):"lokalname"===b?r("location"):a.featureId?r("address"):r("location")}function w(a,b){var f=document.getElementById("dt-search-results");if(f){f.innerHTML="";var d=!1;a&&a.length?a.forEach(function(e){if(e.items&&e.items.length){var g=document.createElement("li");g.className=
"dt-search-group-header";g.setAttribute("role","presentation");g.textContent=e.label;f.appendChild(g);e.items.forEach(function(c){f.appendChild(Q(c));d=!0})}}):b&&b.length&&b.forEach(function(e){f.appendChild(Q(e));d=!0});f.classList.toggle("open",d)}}function ea(a,b){if(!b)return a;var f=b.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");/^CH\d{6,}/i.test(b)&&(b=f.substring(0,2),f=f.substring(2),f=b+"\\s*"+f.split("").join("\\s*"));return a.replace(new RegExp("("+f+")","gi"),'<b class="dt-search-highlight">$1</b>')}
function Q(a){var b=document.createElement("li");b.className="dt-search-item";b.setAttribute("role","option");b.setAttribute("tabindex","-1");var f=da(a),d=ea(a.label||"",R);f=f+'<span class="dt-search-item-text"><span class="dt-search-item-label">'+d+"</span>";return a.subtitle&&(f+='<span class="dt-search-item-subtitle">'+a.subtitle+"</span>"),f+="</span>",b.innerHTML=f,b.addEventListener("click",function(){var e=document.getElementById("dt-search-input"),g=document.getElementById("dt-search-results"),
c=document.getElementById("dt-search-clear");F();if("layer"===a.type){e&&(e.value="");c&&(c.style.display="none");g&&(g.classList.remove("open"),g.innerHTML="");a:{e=a.layer||a.id;if((g=window.TnetLMStore)&&"function"==typeof g.findLayer){if((c=g.findLayer(e))&&"group"!==c.type){g.setLayerVisible(e,!0);TnetLog.log("[DesktopSearch] Layer via Store aktiviert:",e);break a}for(c=e.split("/");1<c.length;){c.pop();var h=c.join("/"),k=g.findLayer(h);if(k&&"group"!==k.type){g.setLayerVisible(h,!0);TnetLog.log("[DesktopSearch] Eltern-Layer aktiviert:",
h,"(statt:",e,")");break a}}}if("function"==typeof window.TnetLayerSwitch)window.TnetLayerSwitch(e,"on");else{try{var l=window.top&&window.top.njs?window.top.njs.AppManager:window.njs?window.njs.AppManager:null;if(l&&"function"==typeof l.setMapBookmark){l.setMapBookmark(["main"],"layers="+e);break a}}catch{}TnetLog.warn("[DesktopSearch] Layer-Aktivierung fehlgeschlagen:",e)}}window.TnetLMTree&&"function"==typeof window.TnetLMTree.navigateToLayer&&window.TnetLMTree.navigateToLayer(a.layer||a.id,a.category)}else"feature"===
a.type||a.featureId?(e&&(e.value=a.label),g&&g.classList.remove("open"),a.layerId&&a.featureId?Z(a):a.x&&a.y&&p(a.x,a.y)):(e&&(e.value=a.label),g&&g.classList.remove("open"),"Parzelle"===a.subtitle&&a.x&&a.y?ca(a.x,a.y):"Adresse"===a.subtitle&&a.x&&a.y?(O(a.x,a.y),p(a.x,a.y,null,.28)):p(a.x,a.y))}),b}function S(a,b){var f=document.querySelector('input[name="dt-canton"]:checked');f=f?f.value:"";var d=document.getElementById("dt-filter-orte"),e=document.getElementById("dt-filter-adressen"),g=document.getElementById("dt-filter-layers");
d=d?d.checked:!0;e=e?e.checked:!0;g=g?g.checked:!0;var c=[];d&&e&&g||(d&&c.push("orte"),e&&c.push("adressen"),!g||c.push("layers"));d=c.join(",");a=fa+"?q="+encodeURIComponent(a)+"&limit=10";return v.maxAddresses&&(a+="&maxAddr="+v.maxAddresses),v.maxLocations&&(a+="&maxLoc="+v.maxLocations),v.maxLayers&&(a+="&maxLay="+v.maxLayers),f&&(a+="&canton="+encodeURIComponent(f)),d&&(a+="&scope="+encodeURIComponent(d)),b&&(a+="&mode="+encodeURIComponent(b)),a}function z(a){if(R=a,L)try{L.abort()}catch{}var b=
++M,f=document.getElementById("dt-filter-layers"),d=(f?f.checked:1)&&I?W(a,10):[];d.length&&w([{label:"Themen",type:"layer",items:d}],null);var e=S(a);if((f=n.get(e))&&3E5>Date.now()-f.ts)w(E(f.data.groups,d),f.data.items);else{var g=S(a,"fast");a=n.get(g);L=f=new AbortController;a&&3E5>Date.now()-a.ts?w(E(a.data.groups,d),a.data.items):fetch(g,{signal:f.signal}).then(function(c){return c.ok?c.json():Promise.reject(c.status)}).then(function(c){M===b&&(50<=n.size&&n.delete(n.keys().next().value),n.set(g,
{data:c,ts:Date.now()}),(!n.has(e)||3E5<=Date.now()-n.get(e).ts)&&w(E(c.groups,d),c.items))}).catch(function(){});fetch(e,{signal:f.signal}).then(function(c){return c.ok?c.json():Promise.reject(c.status)}).then(function(c){M===b&&(50<=n.size&&n.delete(n.keys().next().value),n.set(e,{data:c,ts:Date.now()}),w(E(c.groups,d),c.items))}).catch(function(c){"AbortError"!==c.name&&0===d.length&&w(null,[])})}}function T(){function a(){if(e){var c=document.querySelector('input[name="dt-canton"]:checked');c=
c?c.value:"";var h=document.getElementById("dt-filter-orte"),k=document.getElementById("dt-filter-adressen"),l=document.getElementById("dt-filter-layers");h=h?h.checked:!0;k=k?k.checked:!0;l=l?l.checked:!0;e.classList.toggle("has-filter",!(""===c&&h&&k&&l))}}var b=document.getElementById("dt-search-input"),f=document.getElementById("dt-search-results"),d=document.getElementById("dt-search-clear"),e=document.getElementById("dt-search-filter-btn"),g=document.getElementById("dt-search-filter-popup");
b&&f&&(e&&g&&e.addEventListener("click",function(c){c.stopPropagation();c=g.classList.toggle("open");e.classList.toggle("active",c)}),a(),g&&g.addEventListener("change",function(){a();var c=b.value.trim();3<=c.length&&z(c)}),b.addEventListener("input",function(){var c=b.value.trim();(d&&(d.style.display=c?"flex":"none"),N&&clearTimeout(N),3>c.length)?(f.classList.remove("open"),f.innerHTML=""):N=setTimeout(function(){z(c)},280)}),d&&d.addEventListener("click",function(){b.value="";d.style.display=
"none";f.classList.remove("open");f.innerHTML="";F();b.focus()}),b.addEventListener("keydown",function(c){var h=f.querySelectorAll(".dt-search-item");"Enter"===c.key&&(h.length?h[0].click():3<=b.value.trim().length&&z(b.value.trim()),c.preventDefault());"Escape"===c.key&&(f.classList.remove("open"),b.blur());"ArrowDown"===c.key&&h.length&&(h[0].focus(),c.preventDefault(),c.stopPropagation())}),f.addEventListener("keydown",function(c){var h=f.querySelectorAll(".dt-search-item"),k=Array.prototype.indexOf.call(h,
document.activeElement);"ArrowDown"===c.key&&k<h.length-1&&(h[k+1].focus(),c.preventDefault(),c.stopPropagation());"ArrowUp"===c.key&&(0<k?h[k-1].focus():b.focus(),c.preventDefault(),c.stopPropagation());"Enter"===c.key&&0<=k&&h[k].click();"Escape"===c.key&&(f.classList.remove("open"),b.focus())}),document.addEventListener("click",function(c){c.target.closest("#dt-search-bar")||f.classList.remove("open");g&&!c.target.closest("#dt-search-filter-popup")&&!c.target.closest("#dt-search-filter-btn")&&
(g.classList.remove("open"),e&&e.classList.remove("active"))}),b.addEventListener("focus",function(){3<=b.value.trim().length&&!f.children.length&&z(b.value.trim())}))}function ha(){function a(f){return f>=b.length?Promise.resolve(null):fetch(b[f]).then(function(d){if(!d.ok)throw Error(d.status);return d.text()}).then(function(d){d=JSON5.parse(d);return d&&d.search&&d.search.zoom&&(C=d.search.zoom),d&&d.search&&(v={maxAddresses:d.search.maxAddresses||0,maxLocations:d.search.maxLocations||0,maxLayers:d.search.maxLayers||
0}),d&&d.search?d.search:null}).catch(function(){return a(f+1)})}if("u"<typeof JSON5)return Promise.resolve(null);var b=[x()+"/tnet/config/tnet-global-config.json5",x()+"/tnet/tnet-global-config.json5","../tnet/config/tnet-global-config.json5"];return a(0)}function ia(a){if(a){if(!1===a.njsSearchEnabled){var b=document.getElementById("njs_search_wrapper");b&&(b.style.display="none");TnetLog.log("[DesktopSearch] njs/MapPlus-Suche deaktiviert (Config)")}!1===a.tnetSearchEnabled&&((a=document.getElementById("dt-search-bar"))&&
(a.style.display="none"),TnetLog.log("[DesktopSearch] TNET-Suche deaktiviert (Config)"))}}function U(){T();ha().then(ia);V()}var fa=x()+"/tnet/api/search-proxy.php",N=null,L=null,R="",u=null,C=null,v={},n=new Map,t=null,I=!1,D=!1,X={nidwalden:"NW",obwalden:"OW",bund:"CH",weitere:"Weitere"},Y={nidwalden:0,obwalden:1,bund:2,weitere:3},ja=x()+"/tnet/resources/icons/",H={},K={layer:'<svg class="dt-search-item-icon" viewBox="0 0 24 24"><path d="M11.99 2L2 7l10 5 10-5-10.01-5zM2 17l10 5 10-5-10-5-10 5zM2 12l10 5 10-5-10-5-10 5z"/></svg>',
location:'<svg class="dt-search-item-icon" viewBox="0 0 24 24"><path d="M12 2C8.13 2 5 5.13 5 9c0 5.25 7 13 7 13s7-7.75 7-13c0-3.87-3.13-7-7-7zm0 9.5c-1.38 0-2.5-1.12-2.5-2.5S10.62 6.5 12 6.5s2.5 1.12 2.5 2.5S13.38 11.5 12 11.5z"/></svg>',address:'<svg class="dt-search-item-icon" viewBox="0 0 24 24"><path d="M10 20v-6h4v6h5v-8h3L12 3 2 12h3v8z"/></svg>',street:'<svg class="dt-search-item-icon" viewBox="0 0 24 24"><path d="M11 2h2v4h-2V2zm0 6h2v4h-2V8zm0 6h2v4h-2v-4zm0 6h2v2h-2v-2zM4 2h3v20H4V2zm13 0h3v20h-3V2z"/></svg>',
terrain:'<svg class="dt-search-item-icon" viewBox="0 0 24 24"><path d="M14 6l-3.75 5 2.85 3.8-1.6 1.2C9.81 13.75 7 10 7 10l-6 8h22L14 6z"/></svg>'};["layer","location","address","street","terrain"].forEach(function(a){H[a]||(H[a]=K[a]||K.location,fetch(ja+"search-"+a+".svg").then(function(b){return b.ok?b.text():Promise.reject(b.status)}).then(function(b){H[a]=b.replace("<svg",'<svg class="dt-search-item-icon"')}).catch(function(){}))});var M=0;"loading"===document.readyState?document.addEventListener("DOMContentLoaded",
U):U();window.DesktopSearch={init:T,search:z}})();
