var __tnetInitialUrlLayers=null,__tnetInitialUrlOp=null,__tnetInitialUrlQuery="",__tnetBookmarkAutoStartStarted=!1,__tnetInitialUrlLayerCount=0,__tnetInitialUrlGuardUntil=Date.now()+18E3;
(function(){try{if(/\/maps(?:-dev)?\/[A-Za-z0-9_-]+$/.test(window.location.pathname||"")){var a=new URL(window.location.href);if(a.searchParams.has("layers")||a.searchParams.has("op")){a.searchParams.delete("layers");a.searchParams.delete("op");window.__tnetBookmarkUrlMode="pristine";var b=a.searchParams.toString();window.history.replaceState(null,"",a.pathname+(b?"?"+b:"")+a.hash)}}}catch{}})();
try{__tnetInitialUrlQuery=window.location.search||"";var __tnetInitialUrlParams=new URLSearchParams(window.location.search);__tnetInitialUrlLayers=__tnetInitialUrlParams.get("layers");__tnetInitialUrlOp=__tnetInitialUrlParams.get("op");__tnetInitialUrlLayerCount=__tnetInitialUrlLayers?__tnetInitialUrlLayers.split("|").filter(function(a){return!!a}).length:0}catch{}
__tnetInitialUrlOp&&!window.__tnetInitialOpHistoryGuardInstalled&&function(){function a(e){if(null==e)return e;try{var g=new URL(String(e),window.location.href),c=g.searchParams,h=c.get("layers")||"";h&&h.split("|").filter(function(l){return!!l});var k=__tnetInitialUrlOp.split("|").filter(function(l){return""!==l}).length;return window.__tnetInitialOpHistoryGuardEnabled&&Date.now()<__tnetInitialUrlGuardUntil&&(__tnetInitialUrlLayers&&__tnetInitialUrlLayerCount&&c.set("layers",__tnetInitialUrlLayers),
__tnetInitialUrlOp&&k===__tnetInitialUrlLayerCount&&c.set("op",__tnetInitialUrlOp)),g.pathname+(c.toString()?"?"+c.toString():"")+g.hash}catch{return e}}var b=window.history;if(b&&"function"==typeof b.replaceState){var f=b.replaceState,d=b.pushState;window.__tnetInitialOpHistoryGuardInstalled=!0;window.__tnetInitialOpHistoryGuardEnabled=!0;b.replaceState=function(e,g,c){c=a(c);if(c!==window.location.pathname+window.location.search+window.location.hash)return f.call(this,e,g,c)};"function"==typeof d&&
(b.pushState=function(e,g,c){c=a(c);if(c!==window.location.pathname+window.location.search+window.location.hash)return d.call(this,e,g,c)})}}();
__tnetInitialUrlOp&&!window.__tnetInitialOpStabilizerInstalled&&function(){function a(){try{var d=new URL(window.location.href),e=d.searchParams.get("layers")||"";e&&e.split("|").filter(function(c){return!!c});var g=d.searchParams.get("op")||"";if(Date.now()>=f||Date.now()>=__tnetInitialUrlGuardUntil||!window.__tnetInitialOpHistoryGuardEnabled)return;if(__tnetInitialUrlLayers&&d.searchParams.get("layers")!==__tnetInitialUrlLayers&&d.searchParams.set("layers",__tnetInitialUrlLayers),__tnetInitialUrlOp&&
g!==__tnetInitialUrlOp){d.searchParams.set("op",__tnetInitialUrlOp);b.replaceState(null,"",d.pathname+"?"+d.searchParams.toString()+d.hash);return}__tnetInitialUrlLayers&&d.searchParams.get("layers")!==__tnetInitialUrlLayers&&b.replaceState(null,"",d.pathname+"?"+d.searchParams.toString()+d.hash)}catch{return}"function"==typeof window.requestAnimationFrame?window.requestAnimationFrame(a):setTimeout(a,16)}var b=window.history;if(b&&"function"==typeof b.replaceState){window.__tnetInitialOpStabilizerInstalled=
!0;var f=Date.now()+2E4;a()}}();
function initPanelShadow(){function a(){var c=document.getElementById("spring");if(c){var h=c.querySelectorAll(":scope > .dijitTitlePane");h=0<h.length?h[h.length-1].getBoundingClientRect().bottom+10:f.getBoundingClientRect().bottom}else h=f.getBoundingClientRect().bottom;c=69+(c?c.scrollHeight:400)+10;h>c&&(h=c);c=f.offsetWidth||340;d.style.top="69px";d.style.height=h-69+"px";d.style.width=c+"px";b.classList.contains("close")?(d.style.width="170px",d.style.left="85px",d.style.borderRadius="0 0 4px 4px"):
(d.style.left="0px",d.style.borderRadius="0 0 4px 4px")}var b=document.getElementById("freepane"),f=document.querySelector(".close_switch");if(b&&f){var d=document.createElement("div");d.id="panelShadow";b.parentNode.insertBefore(d,b.nextSibling);a();var e=document.getElementById("spring");if("u">typeof ResizeObserver){var g=new ResizeObserver(a);g.observe(b);g.observe(f);e&&g.observe(e)}(new MutationObserver(a)).observe(b,{attributes:!0,attributeFilter:["class"]});e&&(new MutationObserver(a)).observe(e,
{childList:!0,subtree:!0,attributes:!0,attributeFilter:["class","style"]});document.addEventListener("tnet-app-ready",function(){setTimeout(a,100);setTimeout(a,500)});window.addEventListener("resize",a)}else setTimeout(initPanelShadow,200)}"loading"===document.readyState?document.addEventListener("DOMContentLoaded",initPanelShadow):initPanelShadow();function scrollSpringToTop(){var a=document.getElementById("spring");a&&a.scrollTo({top:0,behavior:"smooth"})}
function initScrollToTop(){var a=document.getElementById("spring"),b=document.getElementById("scrollToTopBtn");a&&b?a.addEventListener("scroll",function(){100<a.scrollTop?b.classList.add("visible"):b.classList.remove("visible")}):setTimeout(initScrollToTop,500)}"loading"===document.readyState?document.addEventListener("DOMContentLoaded",initScrollToTop):initScrollToTop();var __tnetBookmarkNameCache=window.__tnetBookmarkNameCache||{},__tnetBookmarkNameListPromise=null;
window.__tnetBookmarkNameCache=__tnetBookmarkNameCache;function getCachedBookmarkDisplayName(a){a=__tnetBookmarkNameCache&&__tnetBookmarkNameCache[a];return"string"==typeof a&&a?a:null}function rememberBookmarkDisplayNames(a){Array.isArray(a)&&a.forEach(function(b){if(b&&"object"==typeof b){var f=b.id||b["map-bookmark"]||null;b=b.name||b.title||b.label||null;f&&b&&(__tnetBookmarkNameCache[f]=b)}})}
function resolveBookmarkDisplayName(a){var b=getCachedBookmarkDisplayName(a);return b?Promise.resolve(b):window.TnetApi&&"function"==typeof window.TnetApi.listBookmarks?(__tnetBookmarkNameListPromise||=window.TnetApi.listBookmarks().then(function(f){return rememberBookmarkDisplayNames(f),f}).catch(function(){return[]}),__tnetBookmarkNameListPromise.then(function(){return getCachedBookmarkDisplayName(a)})):Promise.resolve(null)}
function announcePendingBookmarkLoad(a,b,f){try{window.__tnetPendingBookmarkLoad={id:a,name:f||null,viewId:b||null,source:"url-autostart",startedAt:Date.now()},document.dispatchEvent(new CustomEvent("tnet-bookmark-loading",{detail:{reason:"url-autostart",pending:window.__tnetPendingBookmarkLoad,bookmark:window.__tnetActiveBookmark||null}}))}catch{}}
function getBookmarkRequestFromUrl(){var a=window.location.pathname.match(/\/maps(?:-dev)?\/([a-zA-Z0-9_-]+)$/);if(!a||!a[1])return null;var b=null,f=__tnetInitialUrlQuery||window.__tnetOriginalUrlQuery||"",d=__tnetInitialUrlLayers||window.__tnetOriginalUrlLayers||null,e=__tnetInitialUrlOp||window.__tnetOriginalUrlOp||null;try{var g=new URLSearchParams(window.location.search),c=g.get("view");c&&/^[a-zA-Z0-9_-]+$/.test(c)&&(b=c);d||=g.get("layers");e||=g.get("op")}catch{}return{bookmarkId:a[1],viewId:b,
initialQuery:f,initialLayers:d,initialOp:e}}function primePendingBookmarkFromUrl(){var a=getBookmarkRequestFromUrl();return a?(announcePendingBookmarkLoad(a.bookmarkId,a.viewId,getCachedBookmarkDisplayName(a.bookmarkId)),resolveBookmarkDisplayName(a.bookmarkId).then(function(b){var f=window.__tnetPendingBookmarkLoad;!b||!f||f.id!==a.bookmarkId||window.__tnetActiveBookmark||announcePendingBookmarkLoad(a.bookmarkId,a.viewId,b)}),a):null}
function startBookmarkFromUrl(){var a=getBookmarkRequestFromUrl();if(a&&a.bookmarkId){let c=function(){if("function"==typeof window.TnetSetBookmark&&window.njs&&window.njs.AppManager&&"function"==typeof window.njs.AppManager.setMapBookmark){var h=d&&/[?&](lang|basemap|blop|x|y|zl|hl|theme|subtheme|layers|op|view)=/.test(d)?{visibleLayerIds:e?e.split("|").filter(function(k){return!!k}):null,originalVisibleLayerIds:e?e.split("|").filter(function(k){return!!k}):null,opacityValues:g?g.split("|"):null,
originalOp:g||"",urlQuery:d,urlOverride:!0}:null;window.TnetSetBookmark(b,f,h)}else setTimeout(c,200)};if(!__tnetBookmarkAutoStartStarted){__tnetBookmarkAutoStartStarted=!0;var b=a.bookmarkId,f=a.viewId,d=a.initialQuery,e=a.initialLayers,g=a.initialOp;primePendingBookmarkFromUrl();c()}}}primePendingBookmarkFromUrl();window._tnetAppReadyFired?startBookmarkFromUrl():document.addEventListener("tnet-app-ready",function(){startBookmarkFromUrl()},{once:!0});setTimeout(startBookmarkFromUrl,1500);
setTimeout(startBookmarkFromUrl,3500);setTimeout(startBookmarkFromUrl,7E3);
