(function(){function p(){return window.__TNET_APP_ROOT||"/maps"}function m(a,b,e){a=document.createElement(a);return b&&(a.className=b),e&&(a.innerHTML=e),a}function u(){var a=m("div","tnet-toc");a.id="tnetToc";var b=m("div","tnet-toc-header");b.innerHTML='<span class="tnet-toc-title">Karten</span><button class="tnet-toc-close" onclick="TnetTOC.close()">&times;</button>';a.appendChild(b);q.sections.forEach(function(e){a.appendChild(v(e))});document.body.appendChild(a);b=m("button","tnet-toc-toggle");
b.id="tnetTocToggle";b.innerHTML="<span>\u2630</span> Karten";b.onclick=function(){TnetTOC.toggle()};document.body.appendChild(b)}function v(a){var b=m("div","tnet-toc-section");b.dataset.sectionId=a.id;var e=m("div","tnet-toc-section-header");e.innerHTML='<img src="'+a.icon+'" alt=""><span>'+a.title+'</span><span class="tnet-toc-section-arrow">\u25b6</span>';e.onclick=function(){var d=a.id,c=document.querySelector('[data-section-id="'+d+'"]');c&&(c.classList.toggle("open"),n.sections[d]=c.classList.contains("open"))};
b.appendChild(e);var g=m("div","tnet-toc-items");return g.id="tnetTocItems_"+a.id,0===a.maps.length?g.innerHTML='<div class="tnet-toc-item" style="color:#999;font-style:italic;">Wird geladen...</div>':a.maps.forEach(function(d){g.appendChild(r(d))}),b.appendChild(g),b}function r(a){var b=m("div","tnet-toc-item");return b.textContent=a.title||a.name,b.dataset.mapId=a.id||a.name,b.onclick=function(){w(a)},b}function w(a){n.activeMap=a.id||a.name;document.querySelectorAll(".tnet-toc-item").forEach(function(e){e.classList.remove("active")});
var b=document.querySelector('[data-map-id="'+n.activeMap+'"]');b&&b.classList.add("active");"function"==typeof window.TnetSetBookmark&&window.TnetSetBookmark(a.url||a.name);TnetTOC.close()}function t(){x.init();y.init();console.log("[tnet-toc-m.js] Accordion/Tab-Konverter initialisiert")}var x={getTabInfo:function(a,b){a=a.querySelectorAll('.dijitTabListWrapper [role="tab"]')[b];b={label:"Kategorie "+(b+1),iconClass:null};a&&(b.label=a.getAttribute("title")||a.textContent.trim()||b.label,a=a.querySelector(".dijitIcon, .dijitTabButtonIcon"))&&
(a=Array.from(a.classList).filter(function(e){return-1!==e.indexOf("njsCategory")||-1!==e.indexOf("Icon")}),a.length&&(b.iconClass=a.join(" ")));return b},convert:function(a){var b=this;if("true"!==a.dataset.tabs2accDone){var e=a.querySelector(".dijitTabPaneWrapper");if(e){var g=e.querySelectorAll(":scope > .dijitTabContainerTopChildWrapper");g.length&&(a.classList.add("tabs2acc-converted"),g.forEach(function(d,c){function f(){var l=h.classList.contains("is-open");h.classList.toggle("is-open",!l);
d.classList.toggle("is-open",!l);d.style.display=l?"none":"block";h.setAttribute("aria-expanded",l?"false":"true")}if(!d.previousElementSibling||!d.previousElementSibling.classList.contains("tabs2acc-header")){c=b.getTabInfo(a,c);var h=document.createElement("div");h.className="tabs2acc-header";h.setAttribute("role","button");h.setAttribute("tabindex","0");h.setAttribute("aria-expanded","false");var k=document.createElement("span");if(k.className="acc-arrow",k.textContent="\u25b6",h.appendChild(k),
c.iconClass)k=document.createElement("span"),k.className="acc-icon dijitIcon "+c.iconClass,h.appendChild(k);k=document.createElement("span");k.textContent=c.label;h.appendChild(k);d.classList.add("tabs2acc-panel");d.classList.remove("dijitVisible","dijitHidden");d.style.display="none";h.addEventListener("click",f);h.addEventListener("keydown",function(l){"Enter"!==l.key&&" "!==l.key||(l.preventDefault(),f())});e.insertBefore(h,d)}}),a.dataset.tabs2accDone="true")}}},processAll:function(){var a=this;
document.querySelectorAll(".dijitTabContainer").forEach(function(b){a.convert(b)})},init:function(){function a(){0<document.querySelectorAll(".dijitTabContainer").length&&b.processAll()}var b=this;if(document.addEventListener("tnet-app-ready",function(){a();setTimeout(a,500)}),window._tnetAppReady&&a(),"u">typeof MutationObserver){var e=document.getElementById("m-layers-sheet")||document.getElementById("kantons_container")||document.getElementById("NeapoljsContainer");e&&(new MutationObserver(function(g){g.some(function(d){return 0<
d.addedNodes.length})&&b.processAll()})).observe(e,{childList:!0,subtree:!0})}}},y={icons:{Nidwalden:p()+"/tnet/resources/wappen_nidwalden.svg",Obwalden:p()+"/tnet/resources/wappen_obwalden.svg",Bund:p()+"/tnet/resources/wappen_bund.svg",Weitere:p()+"/tnet/resources/icon_weitere.svg"},panes:[{id:"tp_layer_menu",name:"Nidwalden"},{id:"tp_layer_menu2",name:"Obwalden"},{id:"tp_layer_menu3",name:"Bund"},{id:"tp_layer_menu4",name:"Weitere"}],convert:function(){var a=this,b=document.getElementById("kantons_container");
if(!b||"true"===b.dataset.tabified||!this.panes.every(function(d){return document.getElementById(d.id)}))return!1;var e=document.createElement("div");e.id="kantons_tab_bar";this.panes.forEach(function(d,c){var f=document.createElement("div");if(f.className="kanton-tab"+(0===c?" active":""),f.dataset.target=d.id,a.icons[d.name])c=document.createElement("img"),c.src=a.icons[d.name],c.alt=d.name,f.appendChild(c);f.title=d.name;f.addEventListener("click",function(){e.querySelectorAll(".kanton-tab").forEach(function(l){l.classList.remove("active")});
a.panes.forEach(function(l){(l=document.getElementById(l.id))&&l.classList.remove("active-tab")});f.classList.add("active");var h=document.getElementById(d.id);if(h){if(h.classList.add("active-tab"),"u">typeof dijit&&"function"==typeof dijit.byId){var k=dijit.byId(d.id);k&&!k.get("open")&&(k._wipeIn?k.set("open",!0):setTimeout(function(){try{k.set("open",!0)}catch{}},200))}a.ensurePaneVisible(h)}});e.appendChild(f)});b.insertBefore(e,b.firstChild);var g=document.getElementById(this.panes[0].id);g&&
g.classList.add("active-tab");return setTimeout(function(){if("u">typeof dijit&&"function"==typeof dijit.byId){var d=dijit.byId(a.panes[0].id);d&&(d.set("open",!0),d.resize&&d.resize())}},300),b.dataset.tabified="true",a.keepPanesOpen(),a.watchThemenkatalog(),!0},ensurePaneVisible:function(a){if(a){var b=a.querySelector(".dijitTitlePaneContentOuter");b&&(b.style.display="block",b.style.height="auto",b.style.overflow="visible",b.style.visibility="visible",(b=b.querySelector('.dijitReset[data-dojo-attach-point="wipeNode"]')||
b.querySelector(".dijitReset")||b.firstElementChild)&&(b.style.display="block",b.style.height="auto",b.style.overflow="visible",b.style.visibility="visible"));(b=a.querySelector(".dijitTitlePaneContentInner"))&&(b.style.display="block",b.style.visibility="visible",b.removeAttribute("aria-hidden"));if(b=a.querySelector(".dijitTitlePaneTitle"))b.classList.remove("dijitTitlePaneTitleClosed","dijitClosed"),b.classList.add("dijitTitlePaneTitleOpen","dijitOpen"),(b=b.querySelector(".dijitTitlePaneTitleFocus"))&&
b.setAttribute("aria-pressed","true");a.classList.remove("dijitTitlePaneClosed","dijitClosed");a.classList.add("dijitTitlePaneOpened")}},keepPanesOpen:function(){"u"<typeof dijit||"function"!=typeof dijit.byId||this.panes.forEach(function(a){(a=dijit.byId(a.id))&&(a._originalToggle=a.toggle,a.toggle=function(){},a._originalSetOpen=a._setOpenAttr,a._setOpenAttr=function(b){this._originalSetOpen&&this._originalSetOpen.call(this,!0)},a.set("open",!0))})},watchThemenkatalog:function(){function a(){var c=
document.getElementById("kantons_tab_bar");if(c&&(c=c.querySelector(".kanton-tab.active"))){c=c.dataset.target;var f=document.getElementById(c);if(f&&(f.classList.add("active-tab"),e.ensurePaneVisible(f),"u">typeof dijit&&"function"==typeof dijit.byId)&&(c=dijit.byId(c))){c._wipeIn=null;c._wipeOut=null;c.open=!0;try{c._setOpenAttr(!0)}catch{}c.hideNode&&(c.hideNode.style.display="block",c.hideNode.style.height="auto");c.wipeNode&&(c.wipeNode.style.display="block",c.wipeNode.style.height="auto");c.resize&&
c.resize()}}}function b(){e.panes.forEach(function(c){(c=document.getElementById(c.id))&&c.classList.contains("dijitTitlePaneClosed")&&(c.classList.remove("dijitTitlePaneClosed"),c.classList.add("dijitTitlePaneOpened"),(c=c.querySelector(".dijitTitlePaneContentOuter"))&&(c.style.display="block",c.style.height="auto"))})}var e=this,g=document.getElementById("kantons_container");if(g&&"u">typeof MutationObserver){var d=null;(new MutationObserver(function(c){d||=requestAnimationFrame(function(){d=null;
b();c.some(function(f){return f.target&&f.target.classList&&(f.target.classList.contains("dijitTitlePane")||f.target.classList.contains("dijitTitlePaneContentOuter")||f.target.classList.contains("dijitReset")||"style"===f.attributeName&&f.target.dataset&&"wipeNode"===f.target.dataset.dojoAttachPoint)})&&a()})})).observe(g,{attributes:!0,subtree:!0,attributeFilter:["class","style"]})}document.addEventListener("click",function(c){c.target.closest(".dijitTitlePaneTitle")&&requestAnimationFrame(a)},!0)},
init:function(){function a(){if(!b.convert())var e=0,g=setInterval(function(){e++;(b.convert()||10<e)&&clearInterval(g)},500)}var b=this;window._tnetAppReady?a():(document.addEventListener("tnet-app-ready",function(){a()},{once:!0}),setTimeout(function(){a()},5E3))}},q={sections:[{id:"nw",title:"Nidwalden",icon:"resources/wappen_nidwalden.svg",maps:[]},{id:"ow",title:"Obwalden",icon:"resources/wappen_obwalden.svg",maps:[]},{id:"ch",title:"Schweiz",icon:"resources/wappen_bund.svg",maps:[]}],bookmarksUrl:"map-bookmarks.json"},
n={isOpen:!1,activeMap:null,sections:{}};window.TnetTOC={init:function(){u();console.log("[TnetTOC] Initialized")},open:function(){var a=document.querySelector("#tnetToc");a&&(a.classList.add("open"),n.isOpen=!0)},close:function(){var a=document.querySelector("#tnetToc");a&&(a.classList.remove("open"),n.isOpen=!1)},toggle:function(){n.isOpen?this.close():this.open()},setMaps:function(a,b){var e=q.sections.find(function(d){return d.id===a});if(e){e.maps=b;var g=document.querySelector("#tnetTocItems_"+
a);g&&(g.innerHTML="",b.forEach(function(d){g.appendChild(r(d))}))}},loadBookmarks:function(a){return a=a||q.bookmarksUrl,fetch(a).then(function(b){return b.json()}).then(function(b){return console.log("[TnetTOC] Bookmarks loaded:",b),b}).catch(function(b){console.error("[TnetTOC] Failed to load bookmarks:",b)})}};"loading"===document.readyState?document.addEventListener("DOMContentLoaded",t):t()})();
