(function(){})();
require("dojo/ready dojo/parser dojo/dom-construct dojo/dom-attr dojo/dom-style dojo/dom-geometry dijit/layout/BorderContainer dijit/layout/ContentPane dijit/TitlePane dijit/Dialog dijit/form/Select dijit/form/Button dijit/form/TextBox dijit/form/CheckBox dijit/Tooltip dijit/form/FilteringSelect dijit/form/Textarea dijit/form/ValidationTextBox dijit/form/RadioButton njs/form/GroupToggleButton njs/data/ComboBoxReadSolrStore dojo/topic dojo/fx dijit/layout/TabContainer dojox/layout/TableContainer".split(" "),function(F,
J,L,M,N){F(function(){function z(e,d){var h=K;e=e.split(".");for(var f=0;f<e.length;f++){if(!(h&&"object"==typeof h&&e[f]in h))return d;h=h[e[f]]}return h??d}var K=window.tnetMobileConfig||{},A=Number(z("sheets.resize.minVh",.3)),B=Number(z("sheets.resize.maxVh",.85)),C=Number(z("sheets.resize.snapCloseVh",.2)),G=Number(z("drawer.autoCloseDelayMs",200)),H=Number(z("timing.drawerInitFallbackMs",3E3)),v=z("timing.layersFixDelaysMs",[100,400,1E3]);0<A&&1>A||(A=.3);B>A&&1>=B||(B=.85);0<C&&1>C||(C=.2);
0<=G||(G=200);0<=H||(H=3E3);Array.isArray(v)&&v.length||(v=[100,400,1E3]);v=v.map(function(e){return Number(e)}).filter(function(e){return!isNaN(e)&&0<=e});v.length||(v=[100,400,1E3]);require(["dojox/layout/FloatingPane"],function(e){try{var d=e.prototype,h=d.show,f=d.close;d.show=function(){this.domNode&&(this.domNode.style.pointerEvents="");h.apply(this,arguments);try{window.dispatchEvent(new CustomEvent("njsInfoPaneShow",{bubbles:!1,detail:{paneId:this.id}}))}catch{}};d.close=function(){f.apply(this,
arguments);this.domNode&&(this.domNode.style.pointerEvents="none");try{window.dispatchEvent(new CustomEvent("njsInfoPaneHide",{bubbles:!1,detail:{paneId:this.id}}))}catch{}}}catch(b){console.warn("[tnet-mobile] FloatingPane prototype patch failed:",b)}});J.parse();v=document.createElement("div");dojo.attr(v,"role","presentation");dojo.attr(v,"id","infolay_wait");dojo.attr(v,"class","infolay_wait");dojo.attr(v,"style","display:none;z-index: 99999;");var I=document.createElement("div");dojo.attr(I,
"class","cube");"front back left right top bottom".split(" ").forEach(function(e){var d=document.createElement("div");dojo.attr(d,"class","face "+e);dojo.place(d,I,"last")});dojo.place(I,v,"last");dojo.place(v,dojo.body(),"first");njs.AppManager.start3D=function(e){var d=njs.AppManager.Maps[e].mapObj.getView().getCenter();"EPSG:2056"!=njs.AppManager.Maps[e].mapObj.getView().getProjection().getCode()&&(d=ol.proj.transform(d,njs.AppManager.Maps[e].mapObj.getView().getProjection().getCode(),"EPSG:2056"));
var h=njs.AppManager.Tools.ElevationDisplay.map.alti1,f=h.cgi.url;f+=-1<f.indexOf("?")?"&":"?";f+="&dbconn_id="+h.cgi.dbconn_id+"&table="+h.cgi.table+"&x="+d[0]+"&y="+d[1]+"&srs="+h.elevationProj.replace("EPSG:","");var b=400;dojo.xhrGet({url:f,preventCache:!0,handleAs:"json",sync:!1,load:function(g){if(g){b=parseFloat(g);g=njs.AppManager.Maps[e].mapObj.getView().getResolution();var k=3E3*g;.4>g&&(k=5E3*g);.2>g&&(k=8E3*g);2E4<k&&(k=2E4);k<b+200&&(k=b+200);d=njs.AppManager.Maps[e].mapObj.getView().getCenter();
"EPSG:4326"!=njs.AppManager.Maps[e].mapObj.getProjection&&(d=ol.proj.transform(d,njs.AppManager.Maps[e].mapObj.getView().getProjection().getCode(),"EPSG:4326"));window.open("https://3d.mapplus.ch/?site=public&basemap=Luftbild&bm_show=1&layers=SWISSTOPO_Buildings,SWISSTOPO_trees&camx="+d[0]+"&camy="+d[1]+"&camz="+k+"&heading=6.283&pitch=-1.571","_blank")}},error:function(g){console.error("elevation service error",g)}})};njs.AppManager.initApp();document.addEventListener("tnet-app-ready",function(){try{for(var e in njs.AppManager.Maps)njs.AppManager.Maps[e].picking=
!0}catch(d){console.warn("[tnet-mobile] picking setzen fehlgeschlagen:",d)}},{once:!0});njs.AppManager.legend_css=["../core/legends/css/geoadmin_legends.css"];window.mDrawerInit=function(){function e(){b.classList.add("open");g.classList.add("open");document.body.style.overflow="hidden"}function d(){b.classList.remove("open");g.classList.remove("open");document.body.style.overflow=""}function h(){document.querySelectorAll(".m-bottom-sheet.open").forEach(function(l){l.classList.remove("open");l.style.height=
""});q&&q.classList.remove("open");var c=document.getElementById("m-basemap-sheet"),a=document.getElementById("m-basemap-overlay");(c&&c.classList.remove("open"),a&&a.classList.remove("open"),"function"==typeof window.closeOerebPanel)&&(c=document.getElementById("oereb-dock-panel"))&&!c.classList.contains("hidden")&&window.closeOerebPanel();"function"==typeof window.closePrintPanel&&(c=document.getElementById("print-panel"))&&!c.classList.contains("hidden")&&window.closePrintPanel();(c=document.getElementById("njs_info_pane"))&&
"hidden"!==c.style.visibility&&((a="u">typeof dijit&&dijit.byId&&dijit.byId("njs_info_pane"))&&a.close?a.close():c.style.visibility="hidden")}var f=document.getElementById("m-hamburger"),b=document.getElementById("m-drawer"),g=document.getElementById("m-drawer-overlay"),k=document.getElementById("m-drawer-close");window.closeDrawer=d;f&&f.addEventListener("click",e);g&&g.addEventListener("click",d);k&&k.addEventListener("click",d);b&&b.addEventListener("click",function(c){for(var a=c.target;a&&a!==
b;){if(a.getAttribute&&"true"===a.getAttribute("aria-disabled"))return c.preventDefault(),c.stopImmediatePropagation(),!1;a=a.parentElement}},!0);document.querySelectorAll("[data-m-toggle]").forEach(function(c){c.addEventListener("click",function(){var a=this.getAttribute("data-m-toggle");if(a=document.getElementById(a)){var l=a.classList.contains("open");document.querySelectorAll(".m-sub-panel").forEach(function(r){r.classList.remove("open")});document.querySelectorAll("[data-m-toggle]").forEach(function(r){r.classList.remove("expanded")});
l||(a.classList.add("open"),this.classList.add("expanded"))}})});var q=document.getElementById("m-sheet-overlay");q&&q.addEventListener("click",h);window.attachSheetResize=function(c){function a(w){D=!0;u=(w.touches?w.touches[0]:w).clientY;E=n.offsetHeight;n.style.transition="none";w.preventDefault()}function l(w){D&&(n.style.setProperty("height",Math.max(window.innerHeight*A,Math.min(window.innerHeight*B,E+(u-(w.touches?w.touches[0]:w).clientY)))+"px","important"),w.cancelable&&w.preventDefault())}
function r(){if(D&&(D=!1,n.style.transition="",n.offsetHeight<window.innerHeight*C))if(n.style.removeProperty("height"),"m-layers-sheet"===n.id&&window.closeLayersSheet)closeLayersSheet();else if("m-basemap-sheet"===n.id&&window.closeBasemapSheet)closeBasemapSheet();else if("oereb-dock-panel"===n.id&&window.closeOerebPanel)closeOerebPanel();else if("njs_info_pane"===n.id){var w="u">typeof dijit&&dijit.byId&&dijit.byId("njs_info_pane");w&&w.close?w.close():n.style.visibility="hidden"}else n.classList.remove("open"),
q&&q.classList.remove("open")}if(c&&"function"==typeof c.closest&&!c._sheetResizeAttached){c._sheetResizeAttached=!0;var n=c.closest(".m-bottom-sheet")||c.closest("#m-basemap-sheet")||c.closest("#oereb-dock-panel")||c.closest("#njs_info_pane");if(n){var u=0,E=0,D=!1;c.addEventListener("touchstart",a,{passive:!1});c.addEventListener("mousedown",a);document.addEventListener("touchmove",l,{passive:!1});document.addEventListener("mousemove",l);document.addEventListener("touchend",r);document.addEventListener("mouseup",
r)}}};(function(){document.querySelectorAll(".m-bottom-sheet .m-sheet-handle,#m-basemap-sheet .m-sheet-handle,#oereb-dock-panel .m-sheet-handle").forEach(function(c){window.attachSheetResize(c)})})();var m=document.getElementById("m-layers-sheet");window.openLayersSheet=function(){function c(){var l=document.getElementById("kantons_container");l&&!l.querySelector(".dijitTitlePane.active-tab")&&((l=document.getElementById("tp_layer_menu"))&&(l.closest(".dijitTitlePane")||l).classList.add("active-tab"),
(l=document.getElementById("kantons_tab_bar"))&&(l=l.querySelector(".kanton-tab"))&&l.classList.add("active"))}h();var a=document.getElementById("kantons_container");a&&!a.querySelector(".dijitTitlePane.active-tab")&&((a=document.getElementById("tp_layer_menu"))&&(a.closest(".dijitTitlePane")||a).classList.add("active-tab"),(a=document.getElementById("kantons_tab_bar"))&&(a=a.querySelector(".kanton-tab"))&&a.classList.add("active"));m&&(m.style.height="",m.classList.add("open"));q&&q.classList.add("open");
d();c();setTimeout(c,500)};window.closeLayersSheet=function(){m&&m.classList.remove("open");q&&q.classList.remove("open")};m&&(m.addEventListener("pointerdown",function(c){c.stopPropagation()}),m.addEventListener("mousedown",function(c){c.stopPropagation()}));var p=document.getElementById("m-active-sheet");if(window.openActiveSheet=function(){h();p&&(p.style.height="",p.classList.add("open"));d();try{if(window.TnetLMStore&&window.TnetLMStore.isLoaded()){var c=window.TnetLMStore.getActiveLayers();
window.TnetLMActive&&window.TnetLMActive.render(c);console.log("[LM-Modules]","Active-Sheet ge\u00f6ffnet,",c.length,"Layer")}}catch(a){console.error("[LM-Modules]","Render-Fehler beim \u00d6ffnen:",a)}},window.closeActiveSheet=function(){p&&p.classList.remove("open");!document.querySelector(".m-bottom-sheet.open")&&q&&q.classList.remove("open")},p)p.addEventListener("pointerdown",function(c){c.stopPropagation()}),p.addEventListener("mousedown",function(c){c.stopPropagation()}),(f=p.querySelector(".m-sheet-handle"))&&
window.attachSheetResize&&window.attachSheetResize(f);var t=document.getElementById("m-basemap-sheet"),x=document.getElementById("m-basemap-overlay");f=document.getElementById("m-basemap-sheet-close");var y=document.getElementById("basemap_selector");window.openBasemapSheet=function(){h();t&&t.classList.add("open");x&&x.classList.add("open");d()};window.closeBasemapSheet=function(){t&&t.classList.remove("open");x&&x.classList.remove("open")};f&&f.addEventListener("click",closeBasemapSheet);x&&x.addEventListener("click",
closeBasemapSheet);t&&(t.addEventListener("pointerdown",function(c){c.stopPropagation()}),t.addEventListener("mousedown",function(c){c.stopPropagation()}));y&&(y.onclick=function(c){c.stopPropagation();openBasemapSheet()});t&&t.addEventListener("click",function(c){if(c=c.target.closest(".basemap-card")){var a=c.dataset.basemap;a&&(document.querySelectorAll(".basemap-card").forEach(function(l){l.classList.remove("active")}),c.classList.add("active"),window.njs&&njs.AppManager&&njs.AppManager.Maps&&
njs.AppManager.Maps.main&&njs.AppManager.Maps.main.changeBaseMap(a),updateBasemapSelectorPreview(a,c))}});window.updateBasemapSelectorPreview=function(c,a){if(y){var l=y.querySelector(".basemap-preview");c=y.querySelector(".basemap-label");if(l&&a){var r=a.querySelector(".basemap-card-preview");if(r){var n="orthofoto basisplan grundbuch landeskarte siegfried dufour transparent keine osm swisstlm".split(" ");n.forEach(function(u){l.classList.remove(u)});n.forEach(function(u){r.classList.contains(u)&&
l.classList.add(u)})}}c&&a&&(a=a.querySelector(".basemap-card-label"))&&(c.textContent=a.textContent)}};(f=t?t.querySelector(".basemap-card.active"):null)&&updateBasemapSelectorPreview(f.dataset.basemap||"",f);document.querySelectorAll(".m-menu-item[data-m-action]").forEach(function(c){c.addEventListener("click",function(){setTimeout(d,G)})})};document.addEventListener("tnet-app-ready",function(){window.mDrawerInit&&mDrawerInit();var e=window.TnetUtils&&TnetUtils.getMainMap?TnetUtils.getMainMap():
null;if(e){var d="",h=0;e.getLayers().on("add",function(f){var b=f.element;b&&b.getSource&&(f=b.getSource())&&f.on&&(f.on("imageloaderror",function(){var g=b.get("title")||b.get("name")||"Layer",k=Date.now();(g!==d||5E3<k-h)&&(d=g,h=k,window.TnetUtils&&TnetUtils.showToast&&TnetUtils.showToast('Layer "'+g+'" konnte nicht geladen werden.',3E3))}),f.on("tileloaderror",function(){var g=b.get("title")||b.get("name")||"Layer",k=Date.now();(g!==d||5E3<k-h)&&(d=g,h=k,window.TnetUtils&&TnetUtils.showToast&&
TnetUtils.showToast('Layer "'+g+'" konnte nicht geladen werden.',3E3))}))})}});window.addEventListener("unhandledrejection",function(e){if(e&&e.reason){var d=(e.reason.message||String(e.reason)).toLowerCase();(-1!==d.indexOf("unexpected token")||-1!==d.indexOf("json")||-1!==d.indexOf("encodingerror")||-1!==d.indexOf("source image"))&&(e.preventDefault(),window.TnetUtils&&TnetUtils.showToast&&TnetUtils.showToast("Fehler beim Laden von Layerdaten.",3E3))}});setTimeout(function(){window.mDrawerInit&&
mDrawerInit()},H);(function(){function e(f){clearTimeout(d);d=setTimeout(function(){if(window._tnetBlockResize)window.FEATURE_FLAGS&&window.FEATURE_FLAGS.DEBUG_MODE&&console.log("[Layout] Resize blocked (_tnetBlockResize): "+f);else try{var b=dijit.byId("NeapoljsContainer");b&&"function"==typeof b.resize&&(b.resize(),window.FEATURE_FLAGS&&window.FEATURE_FLAGS.DEBUG_MODE&&console.log("[Layout] BorderContainer.resize() triggered: "+f))}catch(g){console.error("[Layout] Resize failed:",g.message)}},200)}
var d=null,h=window.innerHeight;window.addEventListener("orientationchange",function(){setTimeout(function(){e("orientationchange")},50)});window.addEventListener("resize",function(){var f=window.innerHeight;f!==h&&(h=f,e("resize"))})})();(function(){var e="top right bottom left width height max-width".split(" "),d=new MutationObserver(function(){var f=document.getElementById("print-panel");f&&(f.classList.contains("hidden")||requestAnimationFrame(function(){e.forEach(function(g){f.style.removeProperty(g)});
var b=document.getElementById("mapContainer");b&&b.style.setProperty("width","100%","important")}))}),h=new MutationObserver(function(){var f=document.getElementById("print-panel");f&&(h.disconnect(),d.observe(f,{attributes:!0,attributeFilter:["class","style"]}))});h.observe(document.body,{childList:!0,subtree:!0})})();(function(){var e=document.getElementById("oereb-dock-panel");if(e){Object.defineProperty(window,"isOerebPanelDocked",{get:function(){return!1},set:function(){},configurable:!0});var d=
document.createElement("div");d.className="m-sheet-handle oereb-sheet-handle";d.innerHTML='<div class="m-sheet-bar"></div>';e.insertBefore(d,e.firstChild);(function g(b){window.attachSheetResize?window.attachSheetResize(d):25>b&&setTimeout(function(){g(b+1)},200)})(0);var h="position top right bottom left width max-height max-width display flex-direction overflow border-radius box-shadow background z-index transform transition".split(" ");h.forEach(function(b){e.style.removeProperty(b)});e.classList.remove("docked-right");
(new MutationObserver(function(){if(!e.classList.contains("hidden")){document.querySelectorAll(".m-bottom-sheet.open").forEach(function(k){k.classList.remove("open");k.style.height=""});var b=document.getElementById("m-sheet-overlay");b&&b.classList.remove("open");b=document.getElementById("m-basemap-sheet");var g=document.getElementById("m-basemap-overlay");b&&b.classList.remove("open");g&&g.classList.remove("open");requestAnimationFrame(function(){h.forEach(function(q){e.style.removeProperty(q)});
e.classList.remove("docked-right");var k=document.getElementById("mapContainer");k&&k.style.setProperty("width","100%","important")})}})).observe(e,{attributes:!0,attributeFilter:["class"]})}})();(function(){function e(b){function g(a){x=!0;p=(a.touches?a.touches[0]:a).clientY;t=b.offsetHeight;b.style.transition="none";a.preventDefault();a.stopPropagation()}function k(a){if(x){var l=Math.max(.2*window.innerHeight,Math.min(.9*window.innerHeight,t+(p-(a.touches?a.touches[0]:a).clientY)));b.style.setProperty("min-height",
l+"px","important");b.style.setProperty("max-height",l+"px","important");a.cancelable&&a.preventDefault()}}function q(){x&&(x=!1,b.style.transition="",b.offsetHeight<.15*window.innerHeight&&(b.style.removeProperty("min-height"),b.style.removeProperty("max-height"),window.closePrintPanel&&window.closePrintPanel()))}var m=document.createElement("div");m.className="m-sheet-handle print-sheet-handle";m.innerHTML='<div class="m-sheet-bar"></div>';m._sheetResizeAttached=!0;b.insertBefore(m,b.firstChild);
var p=0,t=0,x=!1;m.addEventListener("touchstart",g,{passive:!1});m.addEventListener("mousedown",g);document.addEventListener("touchmove",k,{passive:!1});document.addEventListener("mousemove",k);document.addEventListener("touchend",q);document.addEventListener("mouseup",q);var y="position top right bottom left width height max-height max-width border-radius box-shadow z-index transform".split(" "),c=!1;(new MutationObserver(function(){var a=!b.classList.contains("hidden");if(a&&!c){c=!0;document.querySelectorAll(".m-bottom-sheet.open").forEach(function(r){r.classList.remove("open");
r.style.height=""});(a=document.getElementById("m-sheet-overlay"))&&a.classList.remove("open");a=document.getElementById("m-basemap-sheet");var l=document.getElementById("m-basemap-overlay");a&&a.classList.remove("open");l&&l.classList.remove("open");(a=document.getElementById("oereb-dock-panel"))&&!a.classList.contains("hidden")&&window.closeOerebPanel&&closeOerebPanel();window.togglePrintPanelDock&&b.classList.contains("docked-right")&&window.togglePrintPanelDock();requestAnimationFrame(function(){y.forEach(function(n){b.style.removeProperty(n)});
b.classList.remove("docked-right");var r=document.getElementById("mapContainer");r&&r.style.setProperty("width","100%","important")});(a=document.getElementById("print-scale"))&&"1000"!==a.value&&(a.value="1000",a.dispatchEvent(new Event("change",{bubbles:!0})));setTimeout(function(){var r=window._olMap;if(r){var n=r.getView(),u=r.getTargetElement();if(u){n.cancelAnimations();(r=window._printSavedCenter)&&n.setCenter(r);u=u.getBoundingClientRect();var E=b.getBoundingClientRect();u=u.bottom-E.top;
0>u&&(u=0);n.padding=[0,0,u,0];u=1E3*2.8E-4/(n.getProjection().getMetersPerUnit()||1)*4;n.setResolution(u);r&&n.setCenter(r)}}},700)}else!a&&c&&(c=!1,b.style.removeProperty("height"),b.style.removeProperty("min-height"),b.style.removeProperty("max-height"),(a=window._olMap)&&(a.getView().padding=[0,0,0,0]))})).observe(b,{attributes:!0,attributeFilter:["class"]})}var d=document.getElementById("print-panel");if(d)e(d);else var h=0,f=setInterval(function(){d=document.getElementById("print-panel");h++;
d?(clearInterval(f),e(d)):50<h&&clearInterval(f)},200)})();document.addEventListener("tnet-app-ready",function(){function e(){var b=h.getRotation(),g=f.querySelector("svg");g&&(g.style.transform="rotate("+b+"rad)");.01>Math.abs(b)?f.classList.remove("rotated"):f.classList.add("rotated")}var d=window._olMap;if(d){var h=d.getView(),f=document.createElement("div");f.id="m-north-arrow";f.setAttribute("aria-label","Nord ausrichten");f.innerHTML=TnetIcons.get("compass");d.getViewport().appendChild(f);e();
h.on("change:rotation",e);f.addEventListener("click",function(){h.animate({rotation:0,duration:300})})}});document.addEventListener("tnet-app-ready",function(){var e=0;(function h(){window.Landscape3D&&Landscape3D.setupResizer?(Landscape3D.setupResizer.bind(Landscape3D),Landscape3D.setupResizer=function(){function f(m){q.isDragging=!0;var p=document.createElement("div");p.id="drag-overlay-3d";p.style.cssText="position:fixed;top:0;left:0;right:0;bottom:0;z-index:9999;cursor:row-resize;";document.body.appendChild(p);
document.addEventListener("mousemove",b);document.addEventListener("mouseup",g);document.addEventListener("touchmove",b,{passive:!1});document.addEventListener("touchend",g);m.preventDefault()}function b(m){if(q.isDragging){var p=document.getElementById("split-wrapper-3d");if(p){var t=m.touches?m.touches[0].clientY:m.clientY;p=p.getBoundingClientRect();t=Math.max(20,Math.min(80,(t-p.top)/p.height*100));p=document.getElementById("split-panel-2d");var x=document.getElementById("split-panel-3d");p&&
x&&(p.style.flex=t.toString(),x.style.flex=(100-t).toString(),q.dividerPosition=t);q.resize2DMap();m.cancelable&&m.preventDefault()}}}function g(){q.isDragging=!1;var m=document.getElementById("drag-overlay-3d");m&&m.remove();document.removeEventListener("mousemove",b);document.removeEventListener("mouseup",g);document.removeEventListener("touchmove",b);document.removeEventListener("touchend",g);q.resize2DMap()}var k=document.getElementById("split-divider-3d");if(k){var q=Landscape3D;k.addEventListener("mousedown",
f);k.addEventListener("touchstart",f,{passive:!1})}}):20>e++&&setTimeout(h,500)})()})})});function changemappluslang(F){window.location=window.location.href.replace("lang="+njs.AppManager.Language,"lang="+F)};
